### ISSUE TITLE
Issue creation/update fails for versions of Jira prior to 9.x

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#1165]
### Description

As of CxFlow 1.6.37, versions of Jira prior to 9.x throw an exception during the create/update of Jira issues.  It appears the issue is triggered when a Jira custom field is configured to have any default value.

Versions of CxFlow prior to 1.6.37 did not have this issue.

### Expected Behavior

Expect default values in custom fields to not cause an exception.

### Actual Behavior

When a custom field is configured to have a default value, an exception is thrown.

The stack trace is similar to:

```
cxflow-webhook_1  | 2023-01-24 16:22:47.228 ERROR 17 --- [  scan-results1] c.c.f.s.ResultsService                    [AB0ebMMw] : Error occurred while processing results.
cxflow-webhook_1  | 
cxflow-webhook_1  | java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('<This is a schema breaking default value>')
cxflow-webhook_1  |  at [Source: (String)"[{"schema":{"system":"assignee","type":"user"},"hasDefaultValue":false,"operations":["set"],"name":"Assignee","autoCompleteUrl":"http://jira-server:8080/rest/api/latest/user/assignable/search?issueKey=null&username=","required":false,"fieldId":"assignee"},{"schema":{"system":"components","type":"array","items":"component"},"hasDefaultValue":false,"allowedValues":[],"operations":["add","set","remove"],"name":"Component/s","required":false,"fieldId":"components"},{"schema":{"custom":"com.pyxis.gre"[truncated 4580 chars]; line: 1, column: 1064] (through reference chain: java.util.ArrayList[4]->com.checkmarx.flow.jira9X.IssueFields["defaultValue"])
cxflow-webhook_1  |     at com.checkmarx.flow.service.JiraService.getIssueFields(JiraService.java:1256)
cxflow-webhook_1  |     at com.checkmarx.flow.service.JiraService.createIssueTypes(JiraService.java:1147)
cxflow-webhook_1  |     at com.checkmarx.flow.service.JiraService.getMetaData(JiraService.java:1130)
cxflow-webhook_1  |     at com.checkmarx.flow.service.JiraService.lambda$loadCustomFields$6(JiraService.java:1098)
cxflow-webhook_1  |     at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
cxflow-webhook_1  |     at com.checkmarx.flow.service.JiraService.loadCustomFields(JiraService.java:1060)
cxflow-webhook_1  |     at com.checkmarx.flow.service.JiraService.process(JiraService.java:1593)
cxflow-webhook_1  |     at com.checkmarx.flow.service.ResultsService.handleJiraCase(ResultsService.java:232)
cxflow-webhook_1  |     at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:140)
cxflow-webhook_1  |     at com.checkmarx.flow.service.ResultsService.publishCombinedResults(ResultsService.java:101)
cxflow-webhook_1  |     at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)
cxflow-webhook_1  |     at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
cxflow-webhook_1  |     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
cxflow-webhook_1  |     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
cxflow-webhook_1  |     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
cxflow-webhook_1  |     at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:58)
cxflow-webhook_1  |     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
cxflow-webhook_1  |     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
cxflow-webhook_1  |     at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97)
cxflow-webhook_1  |     at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
cxflow-webhook_1  |     at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
cxflow-webhook_1  |     at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
cxflow-webhook_1  |     at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:278)
cxflow-webhook_1  |     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
cxflow-webhook_1  |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
cxflow-webhook_1  |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
cxflow-webhook_1  |     at java.lang.Thread.run(Thread.java:750)
cxflow-webhook_1  | Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('<This is a schema breaking default value>')
cxflow-webhook_1  |  at [Source: (String)"[{"schema":{"system":"assignee","type":"user"},"hasDefaultValue":false,"operations":["set"],"name":"Assignee","autoCompleteUrl":"http://jira-server:8080/rest/api/latest/user/assignable/search?issueKey=null&username=","required":false,"fieldId":"assignee"},{"schema":{"system":"components","type":"array","items":"component"},"hasDefaultValue":false,"allowedValues":[],"operations":["add","set","remove"],"name":"Component/s","required":false,"fieldId":"components"},{"schema":{"custom":"com.pyxis.gre"[truncated 4580 chars]; line: 1, column: 1064] (through reference chain: java.util.ArrayList[4]->com.checkmarx.flow.jira9X.IssueFields["defaultValue"])
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1733)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1358)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.std.StdDeserializer._deserializeFromString(StdDeserializer.java:311)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:454)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:314)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
cxflow-webhook_1  |     at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3660)
cxflow-webhook_1  |     at com.checkmarx.flow.service.JiraService.getIssueFields(JiraService.java:1252)
cxflow-webhook_1  |     ... 26 common frames omitted
cxflow-webhook_1  |
```

### Reproduction

1. Running CxFlow 1.6.37 (web hook mode, should do the same in CLI mode)
2. Run Jira 8.22.6 with a custom field configuration (description below)
3. Execute a scan

### Example of Custom Field Configuration
Select "Custom Fields" in the Issues administration panel.
![image](https://user-images.githubusercontent.com/29153509/214372457-180dd2b2-aeee-42bb-8f0a-8be983ff38da.png)

Click "Add custom field"
![image](https://user-images.githubusercontent.com/29153509/214372608-605ff6a7-eac3-482f-93b3-4a3fe57f86c6.png)

Select multi-line text field
![image](https://user-images.githubusercontent.com/29153509/214372674-00cb59ec-00c9-4668-a619-866d1f4acde1.png)

Give it a name
![image](https://user-images.githubusercontent.com/29153509/214372705-2f35d3d0-5427-471a-8b49-9312faa6982e.png)

Apply to all issues
![image](https://user-images.githubusercontent.com/29153509/214372795-0e20807e-4066-4095-b57f-5f0f7eaa2bc9.png)

Select the default screens and click Update
![image](https://user-images.githubusercontent.com/29153509/214372865-cb5706da-e7cd-4a7c-aadf-54262c093a54.png)

Configure the custom field with the dropdown from `...`
![image](https://user-images.githubusercontent.com/29153509/214373007-cee267c0-2fef-4b47-85ec-74d618c76499.png)

Edit the default value
![image](https://user-images.githubusercontent.com/29153509/214373175-5625a2b9-1966-4959-85b8-8469a0197011.png)

Create an issue and scroll down to validate the custom field appears on the issue screen
![image](https://user-images.githubusercontent.com/29153509/214373219-c751d080-fed3-40ba-8db3-7e2d01a8eb5f.png)

### Environment Details

CxFlow 1.6.37+
Jira 8.22.6 was used for testing, it is presumed any 8.x version of Jira would have the issue.

**Comment by itsKedar** [comment]
Fixed in 1.6.39
