### ISSUE TITLE
Update to GitLab Security Dashboard

### ISSUE THREAD

**Issue by jbrotsos** [checkmarx-ltd/cx-flow#388]
### Description

> GitLab has a new format for their Security Dashboard.  We currently support version 2.0 but they have a 3.0.1 version.  The new version has a few different fields in the scanner section.

### Expected Behavior

A new vendor section has been created that will display the SAST vendor.  The new format looks like this:

report = {
  "version": "3.0.1",
  "scan": {
    "scanner":{
      "id": "checkmarx_scanner",
      "name": Checkmarx Scanner"
      "vendor": {
          "name": "Checkmarx"
       },
    "version": "9.0"
     },

### Actual Behavior

We don't display the Vendor and it defaults to "GitLab" instead of Checkmarx

![gitlab1](https://user-images.githubusercontent.com/10178859/90471212-6e822b80-e0d2-11ea-94e1-adbe55da81cf.png)

### Reproduction

Follow directions here at checkmarx.com/gitlab with the BUG_TRACKER "GitLabDashboard"

### Environment Details

This was hard for me to fix myself in the code because it needs to run within GitLab (the runner creates the artifact)

**Comment by kmcdon83** [comment]
@jbrotsos will be fixed shortly

**Comment by brenwhyte** [comment]
Currently hitting an issue with webhook setup an it failing to update the GitLab dashboard.
Is updating the dashboard currently supported via webhook?

I get the below error when the default branch tries to update the dashboard:

`2020-10-22 17:17:55.755 INFO 1 --- [ scan-results1] c.c.flow.service.ThresholdValidatorImpl : Finding counts: {"HIGH":1,"MEDIUM":18,"LOW":27}

2020-10-22 17:17:55.765 INFO 1 --- [ scan-results1] jsonLogger :

2020-10-22 17:17:55.786 INFO 1 --- [ scan-results1] c.checkmarx.flow.service.ResultsService : Issue tracking is custom bean implementation

2020-10-22 17:17:55.792 ERROR 1 --- [ scan-results1] c.checkmarx.flow.service.ResultsService : Error occurred while processing results.


java.lang.NullPointerException: null

at com.checkmarx.flow.custom.ImmutableIssueTracker.fileInit(ImmutableIssueTracker.java:78)

at com.checkmarx.flow.custom.GitLabSecurityDashboard.init(GitLabSecurityDashboard.java:31)

at com.checkmarx.flow.service.IssueService.process(IssueService.java:98)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)

at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:774)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)

at com.checkmarx.flow.service.IssueService$$EnhancerBySpringCGLIB$$aec8e5c9.process(<generated>)

at com.checkmarx.flow.service.ResultsService.handleCustomIssueTracker(ResultsService.java:217)

at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:170)

at com.checkmarx.flow.service.ResultsService.publishCombinedResults(ResultsService.java:103)

at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)

at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)

at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)

at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)`

I'm almost sure I seen this working with the GitLab CI setup.

**Comment by jbrotsos** [comment]
Closing old features that will not be implemented with CxFlow.
