### ISSUE TITLE
GitLab Security Dashboard and Webhooks error: ImmutableIssueTracker

### ISSUE THREAD

**Issue by brenwhyte** [checkmarx-ltd/cx-flow#478]
### Description

Trying to run with the webhook setup and GitLab.
I configure CxFlow to also use GitLabDashboard  as an issue tracker.

> Provide a description of the issue

Scan runs ok but when updating the GitLabDashboard an error is thrown

### Expected Behavior
Dashboard gets updated as per the docs.

### Actual Behavior

```
2020-10-22 17:17:55.755 INFO 1 --- [ scan-results1] c.c.flow.service.ThresholdValidatorImpl : Finding counts: {"HIGH":1,"MEDIUM":18,"LOW":27}

2020-10-22 17:17:55.765 INFO 1 --- [ scan-results1] jsonLogger :

2020-10-22 17:17:55.786 INFO 1 --- [ scan-results1] c.checkmarx.flow.service.ResultsService : Issue tracking is custom bean implementation

2020-10-22 17:17:55.792 ERROR 1 --- [ scan-results1] c.checkmarx.flow.service.ResultsService : Error occurred while processing results.


java.lang.NullPointerException: null

at com.checkmarx.flow.custom.ImmutableIssueTracker.fileInit(ImmutableIssueTracker.java:78)

at com.checkmarx.flow.custom.GitLabSecurityDashboard.init(GitLabSecurityDashboard.java:31)

at com.checkmarx.flow.service.IssueService.process(IssueService.java:98)

at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.lang.reflect.Method.invoke(Method.java:498)

at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)

at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:774)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)

at com.checkmarx.flow.service.IssueService$$EnhancerBySpringCGLIB$$aec8e5c9.process(<generated>)

at com.checkmarx.flow.service.ResultsService.handleCustomIssueTracker(ResultsService.java:217)

at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:170)

at com.checkmarx.flow.service.ResultsService.publishCombinedResults(ResultsService.java:103)

at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)

at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)

at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)

at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)

at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)

at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)

at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)

at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

at java.lang.Thread.run(Thread.java:748)
```

### Reproduction
```
cxflow:
  bug-tracker: GitLabDashboard
  bug-tracker-impl:
    - GitLab
    - GitLabDashboard
```

### Environment Details

CxFlow 1.6.11
GitLab.com Gold.

**Comment by kmcdon83** [comment]
@brenwhyte can you please check if you have the file-path attribute under your gitlab block?

Here is what I have in my GitLab setup:

```
cx-flow:
  bug-tracker: GitLabDashboard
  bug-tracker-impl:
    - GitLab
    - GitLabDashboard
  filter-severity:
    - High
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  break-build: false
  enabled-vulnerability-scanners:
#    - sca
    - sast

checkmarx:
  username: xxx
  password: xxx
  client-secret: xxxxxxxxxxxxxxxxxxxx
  base-url: https://xxxxx.checkmarx-ts.com
  url: https://xxxxx.checkmarx-ts.com/cxrestapi
  portal-url: https://ast.dev.checkmarx-ts.com/cxwebinterface/Portal/CxWebService.asmx
  multi-tenant: true
  incremental: true
  scan-preset: Checkmarx Default
  configuration: Default Configuration
  team: \CxServer\SP\Checkmarx
  scan-timeout: 120

gitlab:
  file-path: ./gl-sast-report.json
```

Along with the following in my Gitlab yml:
```
image: docker:latest
services:
  - docker:dind

variables:
    CX_TEAM: \CxServer\SP\Checkmarx

stages:
  - scan
  
cx-scan:
  stage: scan
  image:
    name: docker.io/checkmarx/cx-flow
    entrypoint: ['']
  script:
    - cat ${CX_FLOW_CONFIG} > application.yml
    - ${CX_FLOW_EXE} 
        --scan 
        --cx-team="${CX_TEAM}"
        --cx-project="${CI_PROJECT_NAME}" 
        --app="${CI_PROJECT_NAME}" 
        --f=. 
  only:
    - master
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
```

I will ensure an example is added to our github wiki

**Comment by kmcdon83** [comment]
@brenwhyte Are you running this in WebHook mode? Or through GitLab CI?  We don't currently support the API based calls to create the Dashboard Items.

**Comment by brenwhyte** [comment]
Hi Ken,

Thanks for the super quick reply.
Yes we're are indeed using Webhook mode, likely the solution we'll run with. I did see the Dashboard get updated fine in CI mode and assumed Webhook mode was like-for-like.

Thanks for the clarification.

Is there any time frame for Webhook mode to support updating the Dashboard? (is it even possible?)

And I assume this will also be the case with SCA, it would be great if that also updated the Dashboard. (looking at https://github.com/checkmarx-ltd/cx-flow/issues/389)

Thanks again Ken.

**Comment by kmcdon83** [comment]
@brenwhyte we don't have plans at the moment, but we can take it internally to discuss.  They are very different implementations, one is API driven, the other was a json output, which was easy to support.

I recall when we first tackled this there wasn't API support (though I could be wrong).

Yes, the SCA ticket is the same case, we are adding the results to the GitLab CI approach.

**Comment by brenwhyte** [comment]
OK great, thanks for that. I can discuss my side too, I don't know if that will sway the decision to stay with Webhook mode.
Adding GitLab issues per vulnerability found might be enough, along with the future Jira integration.

Feel free to close this one out.

Thanks again.

**Comment by brenwhyte** [comment]
Oh, can I ask is SCA scanning (with "enabled-vulnerability-scanners") and Jira integration also missing from Webhook mode?

**Comment by kmcdon83** [comment]
Jira will work as a bug-tracker in WebHook mode.  It executes on PUSH event against the protected branches (cx-flow branches config block).  This can be overridden to work with Merge Request as well.

Just ensure you follow all the configuration items for transitions, statuses and custom fields:
https://github.com/checkmarx-ltd/cx-flow/wiki/Bug-Trackers-and-Feedback-Channels#jira

**Comment by brenwhyte** [comment]
Great, thanks for the documentation link Ken.
