### ISSUE TITLE
Error occurred while adding source details to project.  Please ensure GIT is defined within Checkmarx

### ISSUE THREAD

**Issue by kollol2k** [checkmarx-ltd/cx-flow#510]
### Description

Integrating with a ADO server (**on-prem**) to decorate pull requests via a CxSAST scan leads to the following errors.

2020-11-09 13:17:28.013 ERROR 5360 --- [flow-web1] com.checkmarx.sdk.service.CxService      : Error occurred while updating Project source info for project 1.
2020-11-09 13:17:28.013 ERROR 5360 --- [flow-web1] c.c.f.s.AbstractVulnerabilityScanner     : SAST scan failed

com.checkmarx.sdk.exception.CheckmarxException: Error occurred while adding source details to project.  Please ensure GIT is defined within Checkmarx
	at com.checkmarx.sdk.service.CxService.setProjectRepositoryDetails(CxService.java:1237)
	at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1666)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scan(AbstractVulnerabilityScanner.java:101)
	at com.checkmarx.flow.service.FlowService.lambda$runScanRequest$3(FlowService.java:61)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.checkmarx.flow.service.FlowService.runScanRequest(FlowService.java:60)
	at com.checkmarx.flow.service.FlowService.initiateAutomation(FlowService.java:39)
	at com.checkmarx.flow.service.FlowService$$FastClassBySpringCGLIB$$3503db27.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Expected Behavior

Scan should be triggered in CxSAST.

### Actual Behavior

Not sure if this observation helps - CxSAST is failing to connect to a Azure DevOps Server (formerly TFS) repo that is git based using a personal access token (PAT). It connects to it using user/password only. However, we need to use PAT to enable CxFlow. 

### Reproduction

> - Log files
[flow.log](https://github.com/checkmarx-ltd/cx-flow/files/5512106/flow.log)

### Environment Details

> CxSAST 9.2 HF4. CxFlow 1.6.12.  The version used is Dev17.M153.5 of Azure DevOps server. Version of Git is 2.29.2.windows.1

**Comment by kmcdon83** [comment]
The log is indicating a 401 for the API token you are using for ADO.  This will also cause the SAST error (though 500 error should never be thrown.  This is an issue from the SAST side).

First message indicating the bad token:
```
2020-11-09 12:45:20.174 DEBUG 9620 --- [http-nio-8982-exec-5] org.apache.http.wire                     : http-outgoing-0 << "[0xef][0xbb][0xbf]{"$id":"1","innerException":null,"message":"TF400813: Resource not available for anonymous access. Client authentication required.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}"
2020-11-09 12:45:20.206 ERROR 9620 --- [http-nio-8982-exec-5] com.checkmarx.flow.service.ADOService    : Error in getting config as code from the repo. Error details : HttpClientErrorException.Unauthorized: 401 Unauthorized: [?{"$id":"1","innerException":null,"message":"TF400813: Resource not available for anonymous access. Client authentication required.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}]
2020-11-09 12:45:20.237 DEBUG 9620 --- [flow-web1] c.c.flow.service.ProjectNameGenerator    : Determining project name for vulnerability scanner.
```

Message from SAST - this will likely be resolved when providing proper token (get passed the 401).:
```
2020-11-09 12:45:35.141 DEBUG 9620 --- [flow-web1] org.apache.http.wire                     : http-outgoing-1 << "}"
2020-11-09 12:45:35.141  WARN 9620 --- [flow-web1] com.checkmarx.sdk.service.CxService      : Error occurred while retrieving project with name InternalDev.JouleTestRunner-dev-jm-find-failed-aat-fix, http error 500 INTERNAL_SERVER_ERROR
2020-11-09 12:45:35.141 ERROR 9620 --- [flow-web1] com.checkmarx.sdk.service.CxService      : org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error: [{
  "messageCode": 500,
  "messag
```

**Comment by kmcdon83** [comment]
@kollol2k  I recommend looking into the health of your SAST instance.  It is throwing a 500 error for every call.  This needs to be resolved before CxFlow can work.
