### ISSUE TITLE
Failed to save project

### ISSUE THREAD

**Issue by kollol2k** [checkmarx-ltd/cx-flow#520]
### Description

> 2020-11-10 11:56:05.652  INFO 30532 --- [      flow-web2] com.checkmarx.sdk.service.CxService      : Creating Project dvcsharp-api-cxbranch for ownerId 10
2020-11-10 11:56:05.653 DEBUG 30532 --- [      flow-web2] o.s.web.client.RestTemplate              : HTTP POST http://localhost/cxrestapi/projects
2020-11-10 11:56:05.657 DEBUG 30532 --- [      flow-web2] o.s.web.client.RestTemplate              : Accept=[text/plain, application/json, application/*+json, */*]
2020-11-10 11:56:05.662 DEBUG 30532 --- [      flow-web2] o.s.web.client.RestTemplate              : Writing [CxCreateProject(id=null, teamId=null, owningTeam=10, name=dvcsharp-api-cxbranch, isPublic=true, links=null)] as "application/json"
2020-11-10 11:56:05.662 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "POST /cxrestapi/projects HTTP/1.1[\r][\n]"
2020-11-10 11:56:05.663 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "Accept: text/plain, application/json, application/*+json, */*[\r][\n]"
2020-11-10 11:56:05.664 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "Authorization: Bearer .....ykSwaeKZuIOUexqMpY78hmRF5ZBToVIivtjyV0j1obNvKZanr2ej8_6vwZKjlcEhemTzUM2JE7l71LFac4bPvVCU80bVQ[\r][\n]"
2020-11-10 11:56:05.664 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "Content-Type: application/json[\r][\n]"
2020-11-10 11:56:05.665 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "Content-Length: 103[\r][\n]"
2020-11-10 11:56:05.665 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "Host: localhost[\r][\n]"
2020-11-10 11:56:05.666 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "Connection: Keep-Alive[\r][\n]"
2020-11-10 11:56:05.666 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "User-Agent: Apache-HttpClient/4.5.10 (Java/1.8.0_221)[\r][\n]"
2020-11-10 11:56:05.667 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "Accept-Encoding: gzip,deflate[\r][\n]"
2020-11-10 11:56:05.673 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "[\r][\n]"
2020-11-10 11:56:05.674 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 >> "{"id":null,"teamId":null,"owningTeam":"10","name":"dvcsharp-api-cxbranch","isPublic":true,"links":null}"
2020-11-10 11:56:05.688 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "HTTP/1.1 400 Bad Request[\r][\n]"
2020-11-10 11:56:05.688 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "Cache-Control: no-cache[\r][\n]"
2020-11-10 11:56:05.692 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "Pragma: no-cache[\r][\n]"
2020-11-10 11:56:05.692 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "Content-Type: application/json; charset=utf-8[\r][\n]"
2020-11-10 11:56:05.693 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "Expires: -1[\r][\n]"
2020-11-10 11:56:05.693 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "Server: Microsoft-IIS/10.0[\r][\n]"
2020-11-10 11:56:05.694 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "X-AspNet-Version: 4.0.30319[\r][\n]"
2020-11-10 11:56:05.694 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "X-Powered-By: ASP.NET[\r][\n]"
2020-11-10 11:56:05.696 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "Date: Tue, 10 Nov 2020 11:56:05 GMT[\r][\n]"
2020-11-10 11:56:05.696 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "Content-Length: 75[\r][\n]"
2020-11-10 11:56:05.696 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "[\r][\n]"
2020-11-10 11:56:05.697 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "{[\r][\n]"
2020-11-10 11:56:05.697 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "  "messageCode": 47823,[\r][\n]"
2020-11-10 11:56:05.698 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "  "messageDetails": "Failed to save project"[\r][\n]"
2020-11-10 11:56:05.705 DEBUG 30532 --- [      flow-web2] org.apache.http.wire                     : http-outgoing-2 << "}"
2020-11-10 11:56:05.706 DEBUG 30532 --- [      flow-web2] o.s.web.client.RestTemplate              : Response 400 BAD_REQUEST
2020-11-10 11:56:05.707 ERROR 30532 --- [      flow-web2] com.checkmarx.sdk.service.CxService      : HTTP error code 400 BAD_REQUEST while creating project with name dvcsharp-api-cxbranch under owner id 10
2020-11-10 11:56:05.708 ERROR 30532 --- [      flow-web2] com.checkmarx.sdk.service.CxService      : org.springframework.web.client.HttpClientErrorException$BadRequest: 400 Bad Request: [{
  "messageCode": 47823,
  "messageDetails": "Failed to save project"
}]
        at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:101)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:170)
        at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:112)
        at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
        at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:782)
        at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:740)
        at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:674)
        at org.springframework.web.client.RestTemplate.postForObject(RestTemplate.java:418)
        at com.checkmarx.sdk.service.CxService.createProject(CxService.java:963)
        at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1656)
        at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scan(AbstractVulnerabilityScanner.java:87)
        at com.checkmarx.flow.service.FlowService.lambda$runScanRequest$3(FlowService.java:61)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.checkmarx.flow.service.FlowService.runScanRequest(FlowService.java:60)
        at com.checkmarx.flow.service.FlowService.initiateAutomation(FlowService.java:39)
        at com.checkmarx.flow.service.FlowService$$FastClassBySpringCGLIB$$3503db27.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

2020-11-10 11:56:05.709 ERROR 30532 --- [      flow-web2] c.c.f.s.AbstractVulnerabilityScanner     : SAST scan failed

com.checkmarx.sdk.exception.CheckmarxException: Project was not created successfully: dvcsharp-api-cxbranch
        at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1658)
        at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scan(AbstractVulnerabilityScanner.java:87)
        at com.checkmarx.flow.service.FlowService.lambda$runScanRequest$3(FlowService.java:61)
        at java.util.ArrayList.forEach(Unknown Source)
        at com.checkmarx.flow.service.FlowService.runScanRequest(FlowService.java:60)
        at com.checkmarx.flow.service.FlowService.initiateAutomation(FlowService.java:39)
        at com.checkmarx.flow.service.FlowService$$FastClassBySpringCGLIB$$3503db27.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

2020-11-10 11:56:05.714  INFO 30532 --- [      flow-web2] jsonLogger                               :
2020-11-10 11:56:05.732  INFO 30532 --- [  scan-results2] c.checkmarx.flow.service.ResultsService  : Finished processing the request

### Reproduction

> Detail the steps taken to reproduce the issue

Scanning a ADO server repo on pull request fails possibly while creating a project 
[flow_azure.log](https://github.com/checkmarx-ltd/cx-flow/files/5517246/flow_azure.log)
> - Log files
attached

### Environment Details

> Ver 1.6.12. SAST ver 9.2 HF4.

**Comment by kmcdon83** [comment]
@kollol2k please take this internally within our Teams channel or CxFlow champions internally.  There appears to be SAST / API issues on your end.  We cannot replicate these issues you are encountering and we should take this conversation internally.

**Comment by Chandram81** [comment]
Please update your user permission to SAST scanner
