### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "String.toUpperCase(java.util.Locale)" because "fieldValue" is null

### ISSUE THREAD

**Issue by Apipia** [checkmarx-ltd/cx-flow#620]
### Description
I am not sure what is going on, the logs are not easy to understand.
Looks like there is some error when downloading/parsing the XML scan report.

### Expected Behavior
No errors

### Actual Behavior
There is an error.
 Report downloaded for report Id 2802
2021-01-25 10:43:20.225  INFO 77516 --- [  scan-results1] c.c.s.s.CxService                         [ZR8tEmnC] : Null Error
2021-01-25 10:43:20.228 ERROR 77516 --- [  scan-results1] c.c.s.s.CxService                         [ZR8tEmnC] : java.lang.NullPointerException: Cannot invoke "String.toUpperCase(java.util.Locale)" because "fieldValue" is null
	at com.checkmarx.sdk.service.FilterValidator.fieldMatches(FilterValidator.java:178)
	at com.checkmarx.sdk.service.FilterValidator.findingPassesFilter(FilterValidator.java:109)
	at com.checkmarx.sdk.service.FilterValidator.passesSimpleFilter(FilterValidator.java:91)
	at com.checkmarx.sdk.service.FilterValidator.passesFilter(FilterValidator.java:61)
	at com.checkmarx.sdk.service.CxService.getIssues(CxService.java:752)
	at com.checkmarx.sdk.service.CxService.getReportContent(CxService.java:435)
	at com.checkmarx.sdk.service.CxService.getReportContentByScanId(CxService.java:364)
	at com.checkmarx.flow.service.ResultsService.processScanResultsAsync(ResultsService.java:61)
	at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)

### Reproduction

The error-throwing line of code is here: https://github.com/checkmarx-ltd/cx-flow/blob/6d23c5c28ac891c63aba28b09e0b3dafeb1ee2f4/src/main/java/com/checkmarx/flow/service/ResultsService.java#L61

The command I'm running is:
java -jar cx-flow-1.6.16-java11.jar --project --cx-team=CxServer/Web Services/XXXXXX --cx-project=XXXXX --app=XXXXX
[cx-flow.log](https://github.com/checkmarx-ltd/cx-flow/files/5868888/cx-flow.log)

**Comment by AvivCx** [comment]
Hi @Apipia
I see the error. we are working to fix it ASAP
Thanks, Aviv

**Comment by AvivCx** [comment]
Hi @Apipia 
issue is resolved in cxflow-1.6.18. 
can you please verify?

**Comment by Apipia** [comment]
@AvivCx 
Verified. It is resolved.
