### ISSUE TITLE
Gitlab Unparseable date on Merge Request scan

### ISSUE THREAD

**Issue by marcandre-larochelle-bell** [checkmarx-ltd/cx-flow#648]
### Description

When using CxFlow for GiLlab integration, it results in an Unparseable date exception.

The date it is trying to format is in has a GMT timezone format ("2021-02-18T17:18:08.362-05:00"), but the code in [GitLabService.java, line 340](https://github.com/checkmarx-ltd/cx-flow/blob/develop/src/main/java/com/checkmarx/flow/service/GitLabService.java#L340) clearly tries to format a RFC 822 timezone format, which results in an exception.

### Expected Behavior

Pull request comment containing the scan is created successfully

### Actual Behavior

```
com.checkmarx.flow.exception.GitLabClientRuntimeException: Error parsing gitlab pull request created or updated date
	at com.checkmarx.flow.service.GitLabService.convertToRepoComment(GitLabService.java:352)
	at com.checkmarx.flow.service.GitLabService.convertToListCxRepoComments(GitLabService.java:330)
	at com.checkmarx.flow.service.GitLabService.getComments(GitLabService.java:324)
	at com.checkmarx.flow.service.RepoService.sendMergeComment(RepoService.java:32)
	at com.checkmarx.flow.service.BugTrackerEventTrigger.triggerScanStartedEvent(BugTrackerEventTrigger.java:38)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.getScanResults(AbstractVulnerabilityScanner.java:132)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:279)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:497)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:555)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:497)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:400)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:83)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: java.text.ParseException: Unparseable date: "2021-02-18T17:18:08.362-05:00"
	at java.text.DateFormat.parse(DateFormat.java:366)
	at com.checkmarx.flow.service.GitLabService.convertToRepoComment(GitLabService.java:347)
```

### Reproduction

Just follow the tutorial: https://checkmarx.atlassian.net/wiki/spaces/SD/pages/1929937052/GitLab+Integration

### Environment Details
Checkmarx version: 8.9.0 HF3, 
GitLab 13.7

**Comment by jbrotsos** [comment]
@marcandre-larochelle-bell can you try it it with this docker image (replace it in the .checkmarx.yml file):

checkmarx/cx-flow:a36d44e

**Comment by jbrotsos** [comment]
Can you schedule some time with me today?  https://calendly.com/james-brotsos

**Comment by jbrotsos** [comment]
I don't see the issue, that is what I'm trying to confirm right away.

It's ok, I'll have a developer look at it next week.

**Comment by marcandre-larochelle-bell** [comment]
Ah, well the issue is trying to parse this date for example: "2021-02-18T17:18:08.362-05:00", the timezone part is in GMT format (-5:00), but the 'Z' specified in `"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'"` (current parsing format used in the code), throws exception if you try to parse a non RFC 822 timezone

As per Oracle doc: [https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html](https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html)

```
Z | Time zone | RFC 822 time zone | -0800
X | Time zone | ISO 8601 time zone | -08; -0800; -08:00

...

For parsing, "Z" is parsed as the UTC time zone designator. General time zones are not accepted.
```

**Comment by marcandre-larochelle-bell** [comment]
Additional info: using docker: checkmarx/cx-flow:1.6.17-8 (release before that line of code was introduced) does not throw an exception.

**Comment by marcandre-larochelle-bell** [comment]
I can confirm the fix done in the latest commit ([https://github.com/checkmarx-ltd/cx-flow/commit/79eac0908197700ebc964e33ae2ee26256caada8](https://github.com/checkmarx-ltd/cx-flow/commit/79eac0908197700ebc964e33ae2ee26256caada8)) fixes it, tried using the docker checkmarx/cx-flow:7414264
