### ISSUE TITLE
Jira cloud Issue #499 broke "assignee" compatibility with Jira Data Center

### ISSUE THREAD

**Issue by nleach999** [checkmarx-ltd/cx-flow#699]
### Description

Issue #499 fixed a problem where Jira cloud `assignee` override broke due to an API change.  The code at the time was using a Jira client library that appears to have abstracted the resolution of the account id.  I believe that client was deprecated, and a change was made to talk directly to the Jira REST API and retrieve `accountId` from the JSON response.  

It appears that the Atlassian announcements referenced in issue #499 applied only to Jira Cloud.  Using Jira Data Center v8.16 (latest), it clearly shows the response payload does not have `accountId` but uses `key` to hold the linking value used for `assignee`.

```
[
	{
		"self": "http://jira-server:8080/rest/api/2/user?username=admin",
		"key": "JIRAUSER10000",
		"name": "admin",
		"emailAddress": "bar@foo.com",
		"avatarUrls": {
			"48x48": "https://www.gravatar.com/avatar/dc8a42aba3651b0b1f088ef928ff3b1d?d=mm&s=48",
			"24x24": "https://www.gravatar.com/avatar/dc8a42aba3651b0b1f088ef928ff3b1d?d=mm&s=24",
			"16x16": "https://www.gravatar.com/avatar/dc8a42aba3651b0b1f088ef928ff3b1d?d=mm&s=16",
			"32x32": "https://www.gravatar.com/avatar/dc8a42aba3651b0b1f088ef928ff3b1d?d=mm&s=32"
		},
		"displayName": "bar@foo.com",
		"active": true,
		"deleted": false,
		"timeZone": "GMT",
		"locale": "en_US"
	}
]

```

### Expected Behavior

The `assignee` override via URL parameter or config-as-code should set the `assignee` field in Jira when creating an issue.  It should probe for `accountId` or `key` to ensure it is compatible with Jira Cloud, Jira Data Center, and any future changes to Jira Data Center should they decide to port the Jira Cloud API changes over to Jira Data Center.

### Actual Behavior

An exception is thrown and all issue creation is aborted.

```
org.json.JSONException: JSONObject["accountId"] not found.
	at org.json.JSONObject.get(JSONObject.java:572)
	at com.checkmarx.flow.service.JiraService.getAssignee(JiraService.java:795)
	at com.checkmarx.flow.service.JiraService.createIssue(JiraService.java:305)
	at com.checkmarx.flow.service.JiraService.createIssueAndAddToNewIssuesList(JiraService.java:1340)
	at com.checkmarx.flow.service.JiraService.process(JiraService.java:1247)
	at com.checkmarx.flow.service.ResultsService.handleJiraCase(ResultsService.java:229)
	at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:137)
	at com.checkmarx.flow.service.ResultsService.publishCombinedResults(ResultsService.java:101)
	at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

### Reproduction

1. Configure CxFlow to use [Jira Data Center](https://hub.docker.com/r/atlassian/jira-software).  In my case, I made an instance using the Docker image.
2. Use a URL or config as code override for `assignee`.
3. Make a change in a protected branch in CxFlow to invoke a scan via webhook, or use some other CxFlow invocation method that will push issues to Jira.
4. Observe exception and issue creation abort.

### Environment Details

Jira Data Center 8.16 (as a Docker image)
CxFlow 1.6.20 (from the `feature/bb_post_webhook` branch merged with head of `develop`)
BitBucket Cloud (using native web hooks)

**Comment by nleach999** [comment]
After some experimentation, Jira actually wants `name` and not `key`.
