### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by boseadler** [checkmarx-ltd/cx-flow#710]
I'm using the Gitlab integration via docker through cxflow and currently I'm stuck at following error messages
![image](https://user-images.githubusercontent.com/74291947/115533810-c693b200-a29f-11eb-8fff-aa831705d0a2.png)

Any ideas ?

**Comment by jbrotsos** [comment]
It's possible running out of memory while zipping the source.

Can you set some time so we can take a look at it (it will faster to just look at it real quick)?

https://calendly.com/james-brotsos

**Comment by boseadler** [comment]
I think we can, unfortunately I'm on EEST, what about you ?

**Comment by jbrotsos** [comment]
> I think we can, unfortunately I'm on EEST, what about you ?

I've update my calendar, please take a look and see if anything fits in for you.

**Comment by boseadler** [comment]
I managed to get the scanning started via the Jenkins plugin but it seems that our project is just too big. over 2 mil files and 100MB archived. After 3 connection retries and around 3 hours of running the scan job stops at 22% done.

**Comment by jbrotsos** [comment]
Please you filters not only on the zip file to remove binary files but also on the scan to remove open source files & test files

**Comment by ahmei0** [comment]
I'm getting exactly the same error on gitlab. Please advise

021-05-05 10:40:42.640  INFO 9 --- [           main] c.c.s.s.CxService                         [WhnbPx5T] : Updating Source details for project Id 234
2021-05-05 10:40:45.048  INFO 9 --- [           main] o.s.s.c.ThreadPoolTaskExecutor            [WhnbPx5T] : Shutting down ExecutorService 'scanRequest'
2021-05-05 10:40:45.049  INFO 9 --- [           main] o.s.s.c.ThreadPoolTaskExecutor            [WhnbPx5T] : Shutting down ExecutorService 'webHook'
2021-05-05 10:40:45.060  INFO 9 --- [           main] ConditionEvaluationReportLoggingListener  [WhnbPx5T] : 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-05-05 10:40:45.079 ERROR 9 --- [           main] o.s.b.SpringApplication                   [WhnbPx5T] : Application run failed
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236)
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
	at org.springframework.util.StreamUtils.copy(StreamUtils.java:167)
	at org.springframework.http.converter.ResourceHttpMessageConverter.writeContent(ResourceHttpMessageConverter.java:137)

**Comment by jbrotsos** [comment]
@ahmei0 are you filtering out files from your zip?  You can do that with the config "--cx-flow.zip-exclude" as described here:  https://github.com/checkmarx-ltd/cx-flow/wiki/Configuration, most likely the GitLab runner is running out memory when zipping.

**Comment by ahmei0** [comment]
@jbrotsos  I'm not using config file. Is there a corresponding environment variable or runtime parameter I can pass to cx-flow jar ?

**Comment by jbrotsos** [comment]
Are you using the template?

If so override the PARAMS variable:

variables:
   PARAMS: --cx-flow.zip-exclude="test"

If that works, I'll add a variable that you can override instead of using PARAMS (i.e. CX_FLOW_ZIP_EXCLUDE)

**Comment by ahmei0** [comment]
what would be the value of this param --cx-flow.zip-exclude ?

**Comment by jbrotsos** [comment]
--cx-flow.zip-exclude="test"

**Comment by jbrotsos** [comment]
Closing this - solved by using zip-exclude
