### ISSUE TITLE
com.checkmarx.flow.exception.MachinaException: Namespace / RepoName / Branch are required

### ISSUE THREAD

**Issue by ahmei0** [checkmarx-ltd/cx-flow#716]
### Description

master branch scan is triggered too when MR is raised as following if condition becomes true.
https://github.com/checkmarx-ltd/cx-flow/blob/develop/templates/gitlab/v2/Checkmarx.gitlab-ci.yml#L67

and this gives following error

2021-04-27 12:02:12.928  INFO 9 --- [           main] c.c.s.s.CxService                         [2BXH0Jha] : Retrieving report contents of report Id 233 in XML format
2021-04-27 12:02:13.343  INFO 9 --- [           main] c.c.s.s.CxService                         [2BXH0Jha] : Report downloaded for report Id 233
2021-04-27 12:02:17.118  INFO 9 --- [           main] c.c.s.s.CxService                         [2BXH0Jha] : Fetching Scan data for Id 1000289
2021-04-27 12:02:17.333  INFO 9 --- [           main] c.c.s.s.CxService                         [2BXH0Jha] : Fetching custom fields from project ID 227
2021-04-27 12:02:17.792  INFO 9 --- [           main] c.c.f.s.ResultsService                    [2BXH0Jha] : Issue tracking is custom bean implementation
2021-04-27 12:02:17.811  INFO 9 --- [           main] c.c.f.c.GitLabIssueTracker                [2BXH0Jha] : Initializing GitLab processing
2021-04-27 12:02:17.820 ERROR 9 --- [           main] c.c.f.CxFlowRunner                        [2BXH0Jha] : An error has occurred.
com.checkmarx.flow.exception.MachinaException: Namespace / RepoName / Branch are required
	at com.checkmarx.flow.custom.GitLabIssueTracker.init(GitLabIssueTracker.java:64)
	at com.checkmarx.flow.service.IssueService.process(IssueService.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)

### Expected Behavior

only MR scan should happen? 
https://github.com/checkmarx-ltd/cx-flow/blob/develop/templates/gitlab/v2/Checkmarx.gitlab-ci.yml#L87

### Actual Behavior

Two scans are triggered as both the conditions becomes true

https://github.com/checkmarx-ltd/cx-flow/blob/develop/templates/gitlab/v2/Checkmarx.gitlab-ci.yml#L67
https://github.com/checkmarx-ltd/cx-flow/blob/develop/templates/gitlab/v2/Checkmarx.gitlab-ci.yml#L90

### Reproduction

Use template as given in https://github.com/checkmarx-ltd/cx-flow/blob/develop/templates/gitlab/v2/Checkmarx.gitlab-ci.yml and create an MR

### Environment Details

> Provide any information relating to the environment the issue was identified in - include applicable version and additional runtime information (include OS or other underlying infrastructure)

**Comment by jbrotsos** [comment]
Hello @ahmei0 

Can you give me a step by step workflow?

**Comment by ahmei0** [comment]
I figured that out. This issue can be closed

**Comment by jbrotsos** [comment]
@ahmei0 great!  Please let me know any feedback from this integration!
