### ISSUE TITLE
CxFlow throws an exception if the --parse option is provided without the --f option

### ISSUE THREAD

**Issue by james-bostock-cx** [checkmarx-ltd/cx-flow#746]
### Description

If CxFlow is invoked with the `--parse` command line option but the `--f` option is not provided,  an exception is thrown.

### Expected Behavior

An error message is printed. E.g., "The --f option must be provided when the --parse option is provided"

### Actual Behavior

```
$ java -jar cx-flow-1.6.21.jar --parse --app=test
   ___             ___ _
  / __\_  __      / __\ | _____      __
 / /  \ \/ /____ / _\ | |/ _ \ \ /\ / /
/ /___ >  <_____/ /   | | (_) \ V  V /
\____//_/\_\    \/    |_|\___/ \_/\_/

2021-06-01 00:43:33.902  INFO 4524 --- [           main] c.c.f.CxFlowApplication                   [] : Starting CxFlowApplication on EC2AMAZ-3JBTK7R with PID 4524 (C:\Users\CxAdmin\Documents\CxFlow\CustomResultStates\cx-flow-1.6.21.jar started by CxAdmin in C:\Users\CxAdmin\Documents\CxFlow\CustomResultStates)
2021-06-01 00:43:33.908  INFO 4524 --- [           main] c.c.f.CxFlowApplication                   [] : No active profile set, falling back to default profiles: default
2021-06-01 00:43:38.374  INFO 4524 --- [           main] ptablePropertiesBeanFactoryPostProcessor  [] : Post-processing PropertySource instances
2021-06-01 00:43:38.533  INFO 4524 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
2021-06-01 00:43:38.535  INFO 4524 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2021-06-01 00:43:38.536  INFO 4524 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-01 00:43:38.536  INFO 4524 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
2021-06-01 00:43:38.536  INFO 4524 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2021-06-01 00:43:38.537  INFO 4524 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource applicationConfig: [file:./application.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-01 00:43:38.537  INFO 4524 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource applicationConfig: [classpath:/application.yml] [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2021-06-01 00:43:38.949  INFO 4524 --- [           main] c.u.j.f.DefaultLazyPropertyFilter         [] : Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
2021-06-01 00:43:38.958  INFO 4524 --- [           main] c.u.j.r.DefaultLazyPropertyResolver       [] : Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
2021-06-01 00:43:38.966  INFO 4524 --- [           main] c.u.j.d.DefaultLazyPropertyDetector       [] : Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
2021-06-01 00:43:39.214  INFO 4524 --- [           main] trationDelegate$BeanPostProcessorChecker  [] : Bean 'org.hibernate.validator.internal.constraintvalidators.bv.NotBlankValidator' of type [org.hibernate.validator.internal.constraintvalidators.bv.NotBlankValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-06-01 00:43:39.219  INFO 4524 --- [           main] trationDelegate$BeanPostProcessorChecker  [] : Bean 'org.hibernate.validator.internal.constraintvalidators.bv.NotNullValidator' of type [org.hibernate.validator.internal.constraintvalidators.bv.NotNullValidator] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-06-01 00:43:39.220  INFO 4524 --- [           main] trationDelegate$BeanPostProcessorChecker  [] : Bean 'flowProperties' of type [com.checkmarx.flow.config.FlowProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-06-01 00:43:39.222  INFO 4524 --- [           main] trationDelegate$BeanPostProcessorChecker  [] : Bean 'flowAsyncConfig' of type [com.checkmarx.flow.config.FlowAsyncConfig$$EnhancerBySpringCGLIB$$473a2586] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2021-06-01 00:43:42.241  INFO 4524 --- [           main] o.s.w.s.s.SaajSoapMessageFactory          [] : Creating SAAJ 1.3 MessageFactory with SOAP 1.1 Protocol
2021-06-01 00:43:43.477  INFO 4524 --- [           main] o.s.s.c.ThreadPoolTaskExecutor            [] : Initializing ExecutorService
2021-06-01 00:43:43.479  INFO 4524 --- [           main] o.s.s.c.ThreadPoolTaskExecutor            [] : Initializing ExecutorService 'scanRequest'
2021-06-01 00:43:43.483  INFO 4524 --- [           main] o.s.s.c.ThreadPoolTaskExecutor            [] : Initializing ExecutorService
2021-06-01 00:43:43.483  INFO 4524 --- [           main] o.s.s.c.ThreadPoolTaskExecutor            [] : Initializing ExecutorService 'webHook'
2021-06-01 00:43:43.497  INFO 4524 --- [           main] c.c.f.CxFlowRunner                        [] : =======BUILD INFO=======
2021-06-01 00:43:43.497  INFO 4524 --- [           main] c.c.f.CxFlowRunner                        [] : Version: cx-flow-1.6.21
2021-06-01 00:43:43.499  INFO 4524 --- [           main] c.c.f.CxFlowRunner                        [] : Time: 2021-06-01T00:00:59.006Z
2021-06-01 00:43:43.499  INFO 4524 --- [           main] c.c.f.CxFlowRunner                        [] : =======================
2021-06-01 00:43:44.652  INFO 4524 --- [           main] c.c.f.CxFlowApplication                   [] : Started CxFlowApplication in 12.503 seconds (JVM running for 13.438)
2021-06-01 00:43:44.668  INFO 4524 --- [           main] c.c.f.CxFlowRunner                        [IdvVIIDY] : Using custom bean implementation  for bug tracking
2021-06-01 00:43:45.042  INFO 4524 --- [           main] c.c.f.s.ScaFilterFactory                  [IdvVIIDY] : Initializing SCA filters.
2021-06-01 00:43:45.046 ERROR 4524 --- [           main] c.c.f.CxFlowRunner                        [IdvVIIDY] : An error occurred while processing request

java.lang.NullPointerException: null
        at java.io.File.<init>(File.java:279)
        at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:358)
        at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:85)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2021-06-01 00:43:45.047  INFO 4524 --- [           main] c.c.f.CxFlowRunner                        [IdvVIIDY] : Finished with exit code: 10
2021-06-01 00:43:45.053  INFO 4524 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskExecutor            [] : Shutting down ExecutorService 'webHook'
2021-06-01 00:43:45.053  INFO 4524 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskExecutor            [] : Shutting down ExecutorService 'scanRequest'
```

### Reproduction

See above (Actual Behavior).

### Environment Details

I am pretty certain that this is independent of the environment. The command line parsing takes place before we try to connect to anything.

**Comment by itsKedar** [comment]
Fixed in 1.6.41
