### ISSUE TITLE
Email bug-tracker not working for CLI mode

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#753]
### Description

In CLI mode, when setting bug-tracker to EMAIL and configuring the SMTP and everything else correctly, CxFlow doesn't send an e-mail when running with either the `--project` to just fetch the results and send the e-mail or when triggering a scan with `--scan` and wait for the result to send an e-mail report (the scan is triggered but an error is immediately thrown afterwards, causing CxFlow not to wait for the scan to finish and send the e-mail afterwards).

NOTE: When using CxFlow in server mode and triggering scans with webhooks, e-mails are sent using the same e-mail configs

### Expected Behavior

An e-mail should be sent out to the recipients after fetching the results or after triggering a scan and waiting for the results.

### Actual Behavior

Two different errors are being sent when running `--project` or `--scan` mode, in scan mode the scan is triggered but CxFlow immediately fails after it triggers it, not waiting for it to finish:

### Reproduction

Config:

```
server:
  port: 8982

logging:
  file:
    name: flow.log

cx-flow:  
  bug-tracker: EMAIL
  #bug-tracker-impl:
  #  - GitHub
  branches:
    - master
  filter-severity:
  filter-category:
  filter-cwe:
  filter-status:
  filter-state:
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  wiki-url: https://checkmarx.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://cxa.codebashing.com/courses/
  contact: example_FROM_mail@mail.com
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: ***
    enabled: true
    cc: example_to_mail@mail.com
    notification: true
    # Send an empty email even if no vulnerabilities found
    allow-empty-mail: false

checkmarx:
  username: cxflowUser
  password: *****
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: http://localhost
  url: ${checkmarx.base-url}/cxrestapi
  team: \CxServer\SP\Company\Users
  scan-preset: High and Medium
  configuration: Default Configuration
  multi-tenant: false
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl

github:
  webhook-token: ***
  token: ***
  url: https://github.com
  api-url: https://api.github.com/repos/
  false-positive-label: false-positive
  block-merge: true
  error-merge: true
  cx-summary-header: AppSec Scan Summary
  cx-summary: true #default false if not provided
  flow-summary-header: Violation Summary
  flow-summary: true #default true if not provided
  detailed-header: AppSec Details
  detailed: true #default true if not provided
  use-config-as-code-from-default-branch: true
```

CLI Commands:

For `--project`:

```
java -jar cx-flow-1.6.21.jar --spring.config.location="application-email.yml" -Dlogging.level.com.checkmarx.flow.service=DEBUG -Dlogging.level.com.checkmarx.flow.utils=DEBUG -Dlogging.level.com.checkmarx.sdk.service=DEBUG --project --cx-team=CxServer\SP\Company\Users --cx-project=CxFlowGithub-master --app=CxFlowGithub-master
```

For `--scan` (after cloning the code locally to `.\CxFlowGithub` directory, but the behavior is similar if using `--github` instead of `--f=.\CxFlowGithub` to have CxSAST to pull the code instead of CxFlow):

```
java -jar cx-flow-1.6.21.jar --spring.config.location="application-email.yml" --scan --f=.\CxFlowGithub --cx-team="CxServer\SP\Company\Users" --cx-project="CxFlowGithub-master" --app="CxFlowGithub-master" --namespace="cx-scord" --repo-name="CxFlowGithub" --repo-url="https://github.com/cx-scord/CxFlowGithub/" --branch="master" --logging.level.com.checkmarx.flow.service=debug --logging.level.com.checkmarx.flow.utils=debug --logging.level.com.checkmarx.sdk.service=debug
```

**Execution Logs:**

Error thrown in  `--project` mode:

```
2021-06-06 11:10:09.185  INFO 67552 --- [           main] com.checkmarx.flow.CxFlowRunner          : =======BUILD INFO=======
2021-06-06 11:10:09.185  INFO 67552 --- [           main] com.checkmarx.flow.CxFlowRunner          : Version: cx-flow-1.6.21
2021-06-06 11:10:09.186  INFO 67552 --- [           main] com.checkmarx.flow.CxFlowRunner          : Time: 2021-06-03T12:49:17.777Z
2021-06-06 11:10:09.187  INFO 67552 --- [           main] com.checkmarx.flow.CxFlowRunner          : =======================
2021-06-06 11:10:10.995  INFO 67552 --- [           main] com.checkmarx.flow.CxFlowApplication     : Started CxFlowApplication in 12.174 seconds (JVM running for 13.3)
2021-06-06 11:10:11.137  INFO 67552 --- [           main] c.c.flow.service.ScaFilterFactory        : Initializing SCA filters.
2021-06-06 11:10:11.142  INFO 67552 --- [           main] com.checkmarx.flow.service.SastScanner   : None of the vulnerability scanners is enabled in the configuration. Using CxSAST scanner by default.
2021-06-06 11:10:11.159  INFO 67552 --- [           main] com.checkmarx.sdk.service.CxAuthService  : Logging into Checkmarx http://localhost/cxrestapi/auth/identity/connect/token
2021-06-06 11:10:11.500  INFO 67552 --- [           main] com.checkmarx.sdk.service.CxService      : Retrieving Cx teams
2021-06-06 11:10:11.530  INFO 67552 --- [           main] com.checkmarx.sdk.service.CxService      : Found team \CxServer\SP\Company\Users with ID 22222222-2222-448d-b029-989c9070eb23
2021-06-06 11:10:11.577  INFO 67552 --- [           main] com.checkmarx.sdk.service.CxService      : Finding last Scan Id for project Id 133
2021-06-06 11:10:11.603  INFO 67552 --- [           main] com.checkmarx.sdk.service.CxService      : Scan found with Id 1000324 for project Id 133
2021-06-06 11:10:11.635  INFO 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Creating report for xml Id 1000324
2021-06-06 11:10:11.655  INFO 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Report with Id 298 created
2021-06-06 11:10:16.664  INFO 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Retrieving report status of report Id 298
2021-06-06 11:10:18.047  INFO 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Retrieving report contents of report Id 298 in XML format
2021-06-06 11:10:18.070  INFO 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Report downloaded for report Id 298
2021-06-06 11:10:19.744  WARN 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Problem grabbing snippet.  Snippet may not exist for finding for Node ID
2021-06-06 11:10:19.817  WARN 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Problem grabbing snippet.  Snippet may not exist for finding for Node ID
2021-06-06 11:10:20.557  INFO 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Fetching Scan data for Id 1000324
2021-06-06 11:10:20.570  INFO 67552 --- [  scan-results1] com.checkmarx.sdk.service.CxService      : Fetching custom fields from project ID 133
2021-06-06 11:10:20.597  INFO 67552 --- [  scan-results1] c.c.flow.service.ThresholdValidatorImpl  : Finding counts: {"HIGH":25,"MEDIUM":73}
2021-06-06 11:10:20.603  INFO 67552 --- [  scan-results1] jsonLogger
2021-06-06 11:16:51.457 ERROR 65552 --- [  scan-results1] c.checkmarx.flow.service.ResultsService  : Error occurred while processing results.

java.lang.NullPointerException: null
        at com.checkmarx.flow.service.ResultsService.getCxFields(ResultsService.java:295)
        at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:128)
        at com.checkmarx.flow.service.ResultsService.processScanResultsAsync(ResultsService.java:66)
        at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

2021-06-06 11:16:51.460 ERROR 65552 --- [           main] com.checkmarx.flow.CxFlowRunner          : An error occurred while processing request

java.util.concurrent.CompletionException: java.lang.NullPointerException
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:279)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException: null
        at com.checkmarx.flow.service.ResultsService.getCxFields(ResultsService.java:295)
        at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:128)
        at com.checkmarx.flow.service.ResultsService.processScanResultsAsync(ResultsService.java:66)
        at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.lambda$doSubmit$3(AsyncExecutionAspectSupport.java:276)
        ... 4 common frames omitted

2021-06-06 11:16:51.461  INFO 65552 --- [           main] com.checkmarx.flow.CxFlowRunner          : Finished with exit code: 10
```

---

Error thrown with `--scan` mode:

```
2021-06-06 11:15:47.296  INFO 34032 --- [           main] com.checkmarx.flow.CxFlowRunner          : =======BUILD INFO=======
2021-06-06 11:15:47.297  INFO 34032 --- [           main] com.checkmarx.flow.CxFlowRunner          : Version: cx-flow-1.6.21
2021-06-06 11:15:47.298  INFO 34032 --- [           main] com.checkmarx.flow.CxFlowRunner          : Time: 2021-06-03T12:49:17.777Z
2021-06-06 11:15:47.299  INFO 34032 --- [           main] com.checkmarx.flow.CxFlowRunner          : =======================
2021-06-06 11:15:49.072  INFO 34032 --- [           main] com.checkmarx.flow.CxFlowApplication     : Started CxFlowApplication in 12.195 seconds (JVM running for 13.28)
2021-06-06 11:15:49.097 DEBUG 34032 --- [           main] c.c.f.service.ScaConfigurationOverrider  : Initializing SCA configuration in scan request using default configuration properties.
2021-06-06 11:15:49.273  INFO 34032 --- [           main] c.c.flow.service.ScaFilterFactory        : Initializing SCA filters.
2021-06-06 11:15:49.281 DEBUG 34032 --- [           main] c.c.flow.service.ScaFilterFactory        : Using SCA filters:
2021-06-06 11:15:49.283  INFO 34032 --- [           main] com.checkmarx.flow.CxFlowRunner          : Executing scan process
2021-06-06 11:15:49.285  INFO 34032 --- [           main] com.checkmarx.flow.service.SastScanner   : None of the vulnerability scanners is enabled in the configuration. Using CxSAST scanner by default.
2021-06-06 11:15:49.286 DEBUG 34032 --- [           main] c.c.flow.service.ProjectNameGenerator    : Determining project name for vulnerability scanner.
2021-06-06 11:15:49.287 DEBUG 34032 --- [           main] c.c.flow.service.ProjectNameGenerator    : Project name override is present. Using the override: CxFlowGithub-master.
2021-06-06 11:15:49.289  INFO 34032 --- [           main] c.c.flow.service.ProjectNameGenerator    : Project name being used: CxFlowGithub-master
2021-06-06 11:15:49.293  INFO 34032 --- [           main] com.checkmarx.flow.utils.ZipUtils        : Creating zip file C:\CxFlowDemo\cx.bf2c1857-1750-419d-81ac-0566f8c77663.zip from contents of path .\CxFlowGithub
2021-06-06 11:15:49.301 DEBUG 34032 --- [           main] com.checkmarx.flow.utils.ZipUtils        : Zip Absolute path: C:\CxFlowDemo\cx.bf2c1857-1750-419d-81ac-0566f8c77663.zip

(...)

2021-06-06 11:15:57.386  INFO 34032 --- [           main] com.checkmarx.flow.utils.ZipUtils        : Successfully created C:\CxFlowDemo\cx.bf2c1857-1750-419d-81ac-0566f8c77663.zip
2021-06-06 11:15:57.386 DEBUG 34032 --- [           main] com.checkmarx.flow.utils.ZipUtils        : Creating temp file C:\CxFlowDemo\cx.bf2c1857-1750-419d-81ac-0566f8c77663.zip
2021-06-06 11:15:57.387 DEBUG 34032 --- [           main] com.checkmarx.flow.utils.ZipUtils        : free space 244934434816
2021-06-06 11:15:57.388 DEBUG 34032 --- [           main] com.checkmarx.flow.utils.ZipUtils        : total space 487037820928
2021-06-06 11:15:57.388 DEBUG 34032 --- [           main] com.checkmarx.flow.utils.ZipUtils        : C:\CxFlowDemo\cx.bf2c1857-1750-419d-81ac-0566f8c77663.zip
2021-06-06 11:15:57.389  INFO 34032 --- [           main] c.c.f.sastscanning.ScanRequestConverter  : Overriding team with \CxServer\SP\Company\Users
2021-06-06 11:15:57.398  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxAuthService  : Logging into Checkmarx http://localhost/cxrestapi/auth/identity/connect/token
2021-06-06 11:15:57.615  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxService      : Retrieving Cx teams
2021-06-06 11:15:57.632  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxService      : Found team \CxServer\SP\Company\Users with ID 22222222-2222-448d-b029-989c9070eb23
2021-06-06 11:15:57.633 DEBUG 34032 --- [           main] c.c.f.s.AbstractVulnerabilityScanner     : Auto profiling is enabled
2021-06-06 11:15:57.647  INFO 34032 --- [           main] c.c.sdk.service.ScanSettingsClientImpl   : Retrieving ScanSettings for project Id 133
2021-06-06 11:15:57.675  INFO 34032 --- [           main] c.c.sdk.service.ScanSettingsClientImpl   : Retrieving preset name for preset Id 3
2021-06-06 11:15:57.698  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxService      : Creating scan...
2021-06-06 11:15:57.698 DEBUG 34032 --- [           main] com.checkmarx.sdk.service.CxService      : CxScanParams{teamName='CxServer\SP\Company\Users', projectName='CxFlowGithub-master', incremental=false, isPublic=true, forceScan=false, fileExclude=null, folderExclude=null, scanPreset='High and Medium', scanConfiguration='null', sourceType=FILE, gitUrl='null', filePath='C:\CxFlowDemo\cx.bf2c1857-1750-419d-81ac-0566f8c77663.zip', customFields=null, postAction='null'}
2021-06-06 11:15:57.725  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxService      : Project's remote settings were not found, http message 404 NOT_FOUND
2021-06-06 11:15:57.726  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxService      : Updating Source details for project Id 133
2021-06-06 11:15:59.919  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxService      : Scan will be Full Scan
2021-06-06 11:15:59.921  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxService      : Creating Scan for project Id 133
2021-06-06 11:15:59.959  INFO 34032 --- [           main] com.checkmarx.sdk.service.CxService      : Scan created with Id 1000325 for project Id 133
2021-06-06 11:16:00.571  INFO 34032 --- [           main] jsonLogger                               :
2021-06-06 11:16:00.580 ERROR 34032 --- [           main] com.checkmarx.flow.CxFlowRunner          : An error occurred while processing request

java.lang.NullPointerException: null
        at com.checkmarx.flow.service.BugTrackerEventTrigger.triggerScanStartedEvent(BugTrackerEventTrigger.java:34)
        at com.checkmarx.flow.service.AbstractVulnerabilityScanner.getScanResults(AbstractVulnerabilityScanner.java:132)
        at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:279)
        at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
        at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:506)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
        at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:565)
        at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:506)
        at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:409)
        at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:85)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
        at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2021-06-06 11:16:00.581  INFO 34032 --- [           main] com.checkmarx.flow.CxFlowRunner          : Finished with exit code: 10
```

### Environment Details

Using CxFlow 1.6.21, CxSAST 8.9 HF24 and latest Java 1.8 in Windows 10.

Similar behavior using CxSAST 9.3 (and adapting the config to use version 9.3).

**Comment by umeshwaghode** [comment]
@cx-scord There are multiple issues being described in the one single issue. Please raise separate issue for separate items.
1. In general email notifications in command line mode, irrespective of bug tracker EMAIL or something else.
2. The support of EMAIL as bug tracker being broken
3. There is also mention of Webhook mode working with email.  Please clarify if this is with EMAIL as bug tracker or general email notifications referred here.

**Comment by cx-scord** [comment]
> @cx-scord There are multiple issues being described in the one single issue. Please raise separate issue for separate items.
> 
> 1. In general email notifications in command line mode, irrespective of bug tracker EMAIL or something else.
> 2. The support of EMAIL as bug tracker being broken
> 3. There is also mention of Webhook mode working with email.  Please clarify if this is with EMAIL as bug tracker or general email notifications referred here.

This is not a "multiple" issues problem, it's a unique issue related to failure of CxFlow using command line mode with `--project` and `--scan` parameters when using EMAIL as a bug-tracker. Basically, it's just related to action 2) of your comment.

The mention to the webhook is just to confirm that in webhook mode the bug-tracker feature is working perfectly OK by having EMAIL as the bug-tracker. It was only broken when using the command line with the 2 parameters above

**Comment by umeshwaghode** [comment]
"An e-mail should be sent out to the recipients after fetching the results or after triggering a scan and waiting for the results." - This is not an expected result for bug-tracker set to EMAIL , is it?

**Comment by cx-scord** [comment]
I assume it should work similarly to any other Bug-trackers that work just by parsing the results from somewhere, be it using `--project`, `--parse`, it should parse the results and do what the implementation is supposed to do, like synchronizing with the popular issue tracker platforms to register/update issues (like in Jira, Github, etc) or like writing the reports to a JSON/XML/CSV file by reading a SAST scan from a CxSAST project, etc...

For example, this is useful on a pipeline when you have a task using CxFlow to trigger a scan and using a regular bug-tracker (like to synchronize the vulnerabilities with the issues on JIRA platform) and, once that task finishes after the scan is executed and the issues synchronized in the bug-tracking platform, then you have another independent task just to send an e-mail through CxFlow using the EMAIL bug-tracker feature.
