### ISSUE TITLE
Zip Uploading to checkmarx stop working

### ISSUE THREAD

**Issue by jbrotsos** [checkmarx-ltd/cx-flow#764]
### Discussed in https://github.com/checkmarx-ltd/cx-flow/discussions/763

<div type='discussions-op-text'>

<sup>Originally posted by **rahul6941** June 22, 2021</sup>
facing issue for uploading zip source to checkmarx. Just let you know that it suddenly stop working and no change 

2021-06-22 20:55:43.015 ERROR 11 --- [           main] c.c.s.s.CxService                         [ez9gnij5] : org.springframework.web.client.HttpServerErrorException$InternalServerError: 500 Internal Server Error: [{
  "messageCode": 500,
  "messageDetails": "Internal Server Error"
}]
	at org.springframework.web.client.HttpServerErrorException.create(HttpServerErrorException.java:100)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:186)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	at org.springframework.web.client.ResponseErrorHandler.handleError(ResponseErrorHandler.java:63)
	at org.springframework.web.client.RestTemplate.handleResponse(RestTemplate.java:780)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:738)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:672)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:581)
	at com.checkmarx.sdk.service.CxService.uploadProjectSource(CxService.java:1314)
	at com.checkmarx.sdk.service.CxService.prepareSources(CxService.java:1738)
	at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1687)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:241)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:278)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:506)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:565)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:506)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:409)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:85)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2021-06-22 21:24:01.412 ERROR 11 --- [           main] c.c.s.s.CxService                         [SWoBc5da] : Error occurred while uploading Project source for project id <id>.
2021-06-22 21:24:01.417 ERROR 11 --- [           main] c.c.f.s.AbstractVulnerabilityScanner      [SWoBc5da] : CheckmarxException: Error occurred while uploading source
com.checkmarx.sdk.exception.CheckmarxException: Error occurred while uploading source
	at com.checkmarx.sdk.service.CxService.uploadProjectSource(CxService.java:1318)
	at com.checkmarx.sdk.service.CxService.prepareSources(CxService.java:1738)
	at com.checkmarx.sdk.service.CxService.createScan(CxService.java:1687)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.executeCxScan(AbstractVulnerabilityScanner.java:241)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:278)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:506)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:565)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:506)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:409)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:85)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)</div>

**Comment by jbrotsos** [comment]
Unable to reproduce
