### ISSUE TITLE
Queuing scans is not allowed for a project with running scans

### ISSUE THREAD

**Issue by cx-scord** [checkmarx-ltd/cx-flow#796]
### Description

When submitting a scan to a project that has an already running scan and no scan slots available, CxFlow doesn't submit it and ends up throwing an error.

There is currently no configuration to allow scans to be queued like it happens when using the UI, developers should not be forced to actively (re)create PRs to see if there's a scan slot available or be completely clueless on whether a push triggered a scan (especially without a configured bug-tracking tool) if they don't have immediate access to the CxSAST UI.

This manifests when:
* A PR scan is happening on the same project and someone pushes directly into the protected branch, the pushed code will not be scanned.
  * This is **critical if a bug-tracker is configured because tickets will not be opened for the protected branch** since the pushed code scan will be cancelled and not queued while another scan is running on that same project.
* Devs use the same CxSAST project for all their repo scans, meaning, either for pushes or PRs. The dev will want the pushed/pulled code scan to be queued and not cancelled.

This could be work as intended for CLI mode (like failing would put a script in a loop waiting to retry the scan), but for Webhook mode is not correct.

### Expected Behavior

It should be possible to configure CxFlow to allow queuing scans if there is already running scans on the same CxSAST project.

This needs to account and cover some possible use cases like:
* With `scan-resubmit` option being true, when a developer resubmit's code to the PR then the **running or queued** scan that matches that branch or feature branch must be cancelled and a new one put in the queue, **without affecting/cancelling any other scans of the same project**. If `sca-resubmit` is false, then the scan shouldn't be replaced.
  * CxFlow is aware of what scan is running for a certain protected/feature branch's PR so this might not be too complex to account for.
* Monitor the CxSAST queue and update the PR scan's check status to let the developer know what's the position in queue of his current scan request. Returning other useful feedback of the queue status for the PR if possible, like the last scan's total running time and average time to finish a scan in the project to improve developers' expectations.
  * It allows for a developer to have more info and waiting and actively trying to resubmit if he's blind to CxSAST's queue status.
* Time out PR queued scans and cancel them that way after a configured amount of time (), code pushed to protected branches should not be timed out.
  * This is because PR scans can push feedback to the developer while pushed can't.

Example of setting this in YAML config:
```yaml
cx-flow:
  scan-queuing: <false|true> ## Defaults to 'false' not to break current behavior.
  scan-queuing-timeout: 720 ## Defaults to 12h. '0' would be for waiting forever with the scan in the queue. Only PR queued scans should be canceled this way, code pushed to protected branches should not be timed out.
 ```

**IMPORTANT**: Issue #496 should be accounted when developing this feature because, once a scan is queued for a certain branch, CxFlow should know which PR matches the requested scan so that the scan being bounded as in #496 will be the same scan of that push/PR request and not a scan from a different feature/protected branch. This will avoid cancelling the wrong scan.

### Actual Behavior

Scans are not queued on pushes or PRs if scans are executing on a project and no scan slots are available.
This is the error being thrown:

This is the error's "template":

```
2021-08-11 23:32:38.378 ERROR 10924 --- [flow-web2] c.c.f.s.AbstractVulnerabilityScanner  : SAST scan failed

com.checkmarx.sdk.exception.CheckmarxException: Active Scan with Id 1021033 already exists for Project: 87
        at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scan(AbstractVulnerabilityScanner.java:84)
        at com.checkmarx.flow.service.FlowService.lambda$runScanRequest$3(FlowService.java:61)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.checkmarx.flow.service.FlowService.runScanRequest(FlowService.java:60)
        at com.checkmarx.flow.service.FlowService.initiateAutomation(FlowService.java:39)
        at com.checkmarx.flow.service.FlowService$$FastClassBySpringCGLIB$$3503db27.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
        at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

### Reproduction

Create 2 PRs, one following the other for the same repo using the same project name (like configuring `project* it in the cx.config).
Also works if creating a PR and pushing code afterwards or vice-versa, the later scan(s) will always fail while a scan slot is not available.

### Environment Details

CxFlow 1.6.22 server, Windows 10

**Comment by HussainS12** [comment]
Fixed in PR #857
