### ISSUE TITLE
Escaping in Jira Project Name

### ISSUE THREAD

**Issue by ankrueger-ih** [checkmarx-ltd/cx-flow#814]
### Description

we cant start a scan using cxflow in parse mode

Within the CxFlow application.yml we have added the project name as:
  project: "CF"

We also already tried 'cf' or escaping of the characters. Nothing works. 

### Expected Behavior
Jira Tickets are created 

### Actual Behavior
we get the error: [ErrorCollection{status=400, errors={}, errorMessages=[Error in JQL Query: Expecting either a value, list or function but got 'CF'. You must surround 'CF' in quotation marks to use it as a value. (line 1, character 11)]}]

### Reproduction
- add a project name to the applicatin.yml file
- start the scan using             java -jar cxflow/cx-flow-1.6.23.jar --parse --branch=master --f=Checkmarx/Reports/ScanReport.xml --app=test --spring.config.location=cxflow/application.yml

2021-09-06 14:48:01.065 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "0[\r][\n]"
2021-09-06 14:48:01.065 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "[\r][\n]"
2021-09-06 14:48:01.075  INFO 30376 --- [           main] c.c.f.s.JiraService                       [bmuH8W3C] : finished Loading 19 new custom fields
2021-09-06 14:48:01.076  INFO 30376 --- [           main] c.c.f.s.JiraService                       [bmuH8W3C] : Processing Results and publishing findings to Jira
2021-09-06 14:48:01.080  INFO 30376 --- [           main] c.c.f.s.JiraService                       [bmuH8W3C] : Executing getIssues API call
2021-09-06 14:48:01.084 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 >> "GET /jira/rest/api/latest/search?jql=project+%3D+CF+and+issueType+%3D+%22Finding%22+and+(%22labels%22+%3D+%22CX%22+and+%22labels%22+%3D+%22app:test%22)&expand=schema,names&fields=summary,issuetype,created,project,updated,key,labels,status&maxResults=50&startAt=0 HTTP/1.1[\r][\n]"
2021-09-06 14:48:01.084 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 >> "Accept: application/json[\r][\n]"
2021-09-06 14:48:01.084 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 >> "Via: 1.1 localhost (Apache-HttpClient/4.5.13 (cache))[\r][\n]"
2021-09-06 14:48:01.084 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 >> "Host: atlant.interhyp-intern.de[\r][\n]"
2021-09-06 14:48:01.084 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
2021-09-06 14:48:01.084 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 >> "User-Agent: Atlassian HttpClient 2.0.0 / Atlassian JIRA Rest Java Client- (0) / Default[\r][\n]"

2021-09-06 14:48:01.084 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 >> "[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "HTTP/1.1 400 [\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Date: Mon, 06 Sep 2021 12:48:00 GMT[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Server: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips mod_auth_kerb/5.4[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "X-AREQUESTID: 888x4859480x1[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "X-ASESSIONID: q66zjz[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "X-ANODEID: atlant2.interhyp-lbdmz.de[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Referrer-Policy: strict-origin-when-cross-origin[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "X-XSS-Protection: 1; mode=block[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "X-Content-Type-Options: nosniff[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "X-Frame-Options: SAMEORIGIN[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Content-Security-Policy: sandbox[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Strict-Transport-Security: max-age=31536000[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "X-Seraph-LoginReason: OK[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "X-AUSERNAME: cx_flow[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Cache-Control: no-cache, no-store, no-transform[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Content-Type: application/json;charset=UTF-8[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Connection: close[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "Transfer-Encoding: chunked[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "c5[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "{"errorMessages":["Error in JQL Query: Expecting either a value, list or function but got 'CF'. You must surround 'CF' in quotation marks to use it as a value. (line 1, character 11)"],"errors":{}}[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "0[\r][\n]"
2021-09-06 14:48:01.096 DEBUG 30376 --- [/O dispatcher 1] o.a.http.wire                             [] : http-outgoing-0 << "[\r][\n]"
2021-09-06 14:48:01.106 ERROR 30376 --- [           main] c.c.f.CxFlowRunner                        [bmuH8W3C] : An error occurred while processing request

due to the following reason: [ErrorCollection{status=400, errors={}, errorMessages=[Error in JQL Query: Expecting either a value, list or function but got 'CF'. You must surround 'CF' in quotation marks to use it as a value. (line 1, character 11)]}]
	at com.checkmarx.flow.service.ResultsService.throwExceptionWhenPublishingErrorOccurred(ResultsService.java:269)
	at com.checkmarx.flow.service.ResultsService.handleJiraRestClientException(ResultsService.java:256)
	at com.checkmarx.flow.service.ResultsService.handleJiraCase(ResultsService.java:231)
	at com.checkmarx.flow.service.ResultsService.processResults(ResultsService.java:137)
	at com.checkmarx.flow.service.ResultsService$$FastClassBySpringCGLIB$$2328645f.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.checkmarx.flow.service.ResultsService$$EnhancerBySpringCGLIB$$f4ba7cf9.processResults(<generated>)
	at com.checkmarx.flow.service.SastScanner.cxParseResults(SastScanner.java:83)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:192)
	at com.checkmarx.flow.CxFlowRunner.lambda$cxParse$2(CxFlowRunner.java:558)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:545)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:608)
	at com.checkmarx.flow.CxFlowRunner.cxParse(CxFlowRunner.java:558)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:400)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:89)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.atlassian.jira.rest.client.api.RestClientException: [ErrorCollection{status=400, errors={}, errorMessages=[Error in JQL Query: Expecting either a value, list or function but got 'CF'. You must surround 'CF' in quotation marks to use it as a value. (line 1, character 11)]}]
	at com.atlassian.jira.rest.client.internal.async.DelegatingPromise.claim(DelegatingPromise.java:45)
	at com.checkmarx.flow.service.JiraService.getIssues(JiraService.java:234)
	at com.checkmarx.flow.service.JiraService.process(JiraService.java:1252)
	at com.checkmarx.flow.service.ResultsService.handleJiraCase(ResultsService.java:229)
	... 38 common frames omitted
Caused by: com.atlassian.jira.rest.client.api.RestClientException: [ErrorCollection{status=400, errors={}, errorMessages=[Error in JQL Query: Expecting either a value, list or function but got 'CF'. You must surround 'CF' in quotation marks to use it as a value. (line 1, character 11)]}]
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:176)
	at com.atlassian.jira.rest.client.internal.async.AbstractAsynchronousRestClient$2.apply(AbstractAsynchronousRestClient.java:170)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:49)
	at com.atlassian.httpclient.api.ResponsePromiseMapFunction.apply(ResponsePromiseMapFunction.java:10)
	at io.atlassian.util.concurrent.Promises$OfStage.lambda$fold$4(Promises.java:332)
	at io.atlassian.util.concurrent.Promises.lambda$biFunction$7(Promises.java:422)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822)
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$1.lambda$doCompleted$0(SettableFuturePromiseHttpPromiseAsyncClient.java:37)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient.runInContext(SettableFuturePromiseHttpPromiseAsyncClient.java:61)
	at com.atlassian.httpclient.apache.httpcomponents.SettableFuturePromiseHttpPromiseAsyncClient$ThreadLocalDelegateRunnable.run(SettableFuturePromiseHttpPromiseAsyncClient.java:129)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Environment Details

We are running cxflow on our Jenkins

**Comment by cx-scord** [comment]
I believe this is a duplicate of #736

**Comment by ankrueger-ih** [comment]
Yes you are absolutely correct, its a duplicate of #736
