### ISSUE TITLE
Allow Symbolic Links

### ISSUE THREAD

**Issue by kayvonkhosrowpour** [checkmarx-ltd/cx-flow#842]
### Describe the problem

CxFlow does not properly zip symbolic link files, failing during zip and not triggering a scan. We currently exclude the files, but this is an unfortunate workaround.

### Proposed solution

When zipping, properly zip symbolic links. Or, provide a configuration flag that will allow zipping symbolic links.

### Additional details

Example failure as of now:
```
2021-10-07 17:44:35.300 ERROR 12 --- [main] c.c.f.s.AbstractVulnerabilityScanner      [iqnZoVFz] : Error occurred while attempting to zip path .
java.io.FileNotFoundException: ./path/to/symbolic_link.tf (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.checkmarx.flow.utils.ZipUtils.addToZip(ZipUtils.java:84)
	at com.checkmarx.flow.utils.ZipUtils.addToZip(ZipUtils.java:70)
	at com.checkmarx.flow.utils.ZipUtils.zipFile(ZipUtils.java:54)
	at com.checkmarx.flow.utils.ZipUtils.zipToTempFile(ZipUtils.java:27)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanLocalPath(AbstractVulnerabilityScanner.java:277)
	at com.checkmarx.flow.service.AbstractVulnerabilityScanner.scanCli(AbstractVulnerabilityScanner.java:189)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:558)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:617)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:558)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:435)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:89)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:786)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:776)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
```

**Comment by satyamchaurasiapersistent** [comment]
Fixed in Release 1.7.04
