### ISSUE TITLE
SCA zip scan fails when run in pipeline

### ISSUE THREAD

**Issue by juegge** [checkmarx-ltd/cx-flow#938]
### Description

When asking for sca zipscan the scan is failing. Pse see the following yml 
include: 'https://raw.githubusercontent.com/checkmarx-ltd/cx-flow/develop/templates/gitlab/v3/Checkmarx.gitlab-ci.yml'

variables:
    CX_FLOW_ENABLED_VULNERABILITY_SCANNERS: "sast,sca"
    CX_TEAM: "/CxServer/SP/EMEA/checkmarx.ch - 972"
    CHECKMARX_USERNAME: $CX_USERNAME
    CHECKMARX_PASSWORD: $CX_PASSWORD
    CHECKMARX_BASE_URL: $CHECKMARX_SERVER
    CHECKMARX_SCAN_PRESET: "OWASP TOP 10 - 2017"
    CHECKMARX_SETTINGS_OVERRIDE: "true"

    SCA_TENANT: $SCA_TENANT
    SCA_USERNAME: $SCA_USERNAME
    SCA_PASSWORD: $SCA_PASSWORD
    SCA_INCLUDESOURCES: "true"
    SCA_ENABLEDZIPSCAN: "true"

### Expected Behavior
Sca scan works

### Actual Behavior
sca scan fails

Log extract:
2022-02-22 07:50:41.621  INFO 11 --- [           main] o.s.w.s.s.SaajSoapMessageFactory          [] : Creating SAAJ 1.3 MessageFactory with SOAP 1.1 Protocol
2022-02-22 07:50:42.942  INFO 11 --- [           main] c.c.f.CxFlowRunner                        [] : =======BUILD INFO=======
2022-02-22 07:50:42.944  INFO 11 --- [           main] c.c.f.CxFlowRunner                        [] : Version: cx-flow-1.6.30
2022-02-22 07:50:42.949  INFO 11 --- [           main] c.c.f.CxFlowRunner                        [] : Time: 2022-02-07T13:29:43.5[53](https://gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab/-/jobs/2121014902#L53)Z
2022-02-22 07:50:42.949  INFO 11 --- [           main] c.c.f.CxFlowRunner                        [] : =======================
2022-02-22 07:50:45.480  INFO 11 --- [           main] c.c.f.CxFlowApplication                   [] : Started CxFlowApplication in 19.205 seconds (JVM running for 20.785)
2022-02-22 07:50:45.509  INFO 11 --- [           main] c.c.f.CxFlowRunner                        [sKWmPf6m] : Using custom bean implementation  for bug tracking
2022-02-22 07:50:45.[60](https://gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab/-/jobs/2121014902#L60)3  INFO 11 --- [           main] c.c.f.s.ScaFilterFactory                  [sKWmPf6m] : Initializing SCA filters.
2022-02-22 07:50:45.605  INFO 11 --- [           main] c.c.f.CxFlowRunner                        [sKWmPf6m] : Executing scan process
2022-02-22 07:50:45.609  INFO 11 --- [           main] c.c.f.s.ScaFilterFactory                  [sKWmPf6m] : Initializing SCA filters.
2022-02-22 07:50:45.620  INFO 11 --- [           main] c.c.f.s.AbstractASTScanner                [sKWmPf6m] : --------------------- Initiating new sca scan ---------------------
2022-02-22 07:50:45.621  INFO 11 --- [           main] c.c.f.s.SCAScanner                        [sKWmPf6m] : CxAST-SCA zip scan is enabled
2022-02-22 07:50:45.625 ERROR 11 --- [           main] c.c.f.s.AbstractASTScanner                [sKWmPf6m] : sca scan failed.
java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(URI.java:3041)
at java.net.URI.<init>(URI.java:588)
	at com.checkmarx.sdk.utils.CxRepoFileHelper.gitClone(CxRepoFileHelper.java:150)
	at com.checkmarx.sdk.utils.CxRepoFileHelper.gitCloneAndRunPostCloneScript(CxRepoFileHelper.java:89)
	at com.checkmarx.sdk.utils.CxRepoFileHelper.getScaClonedRepoFolderPath(CxRepoFileHelper.java:216)
	at com.checkmarx.flow.service.SCAScanner.setScannerSpecificProperties(SCAScanner.java:56)
	at com.checkmarx.flow.service.AbstractASTScanner.toSdkScanParams(AbstractASTScanner.java:138)
	at com.checkmarx.flow.service.AbstractASTScanner.actualScan(AbstractASTScanner.java:118)
	at com.checkmarx.flow.service.AbstractASTScanner.scan(AbstractASTScanner.java:108)
	at com.checkmarx.flow.service.AbstractASTScanner.scanCli(AbstractASTScanner.java:61)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanLocalPath$1(CxFlowRunner.java:5[70](https://gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab/-/jobs/2121014902#L70))
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:4[72](https://gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab/-/jobs/2121014902#L72))
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:629)
	at com.checkmarx.flow.CxFlowRunner.scanLocalPath(CxFlowRunner.java:570)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:443)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:93)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:[74](https://gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab/-/jobs/2121014902#L74)8)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:309)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
2022-02-22 07:50:45.[81](https://gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab/-/jobs/2121014902#L81)4  INFO 11 --- [           main] jsonLogger                                [sKWmPf6m] : 
2022-02-22 07:50:45.[96](https://gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab/-/jobs/2121014902#L96)5 ERROR 11 --- [           main] c.c.f.s.AbstractASTScanner                [sKWmPf6m] : sca scan failed.
null
2022-02-22 07:50:45.965  INFO 11 --- [           main] c.c.f.CxFlowRunner                        [sKWmPf6m] : Finished with exit code: 10

### Reproduction
Use project https://gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab or any other project with a similar yml.

**Comment by juegge** [comment]
basically running a sca scan with cxflow in cli mode and setting --sca.enabledZipScan=true causes the error

**Comment by juegge** [comment]
Ok, I understood that my pipeline that I originally posted was missing a parameter. It should look like this
variables:
    CX_FLOW_ENABLED_VULNERABILITY_SCANNERS: "sca"
    CX_TEAM: "/CxServer/SP/EMEA/checkmarx.ch - 972"
    CHECKMARX_USERNAME: $CX_USERNAME
    CHECKMARX_PASSWORD: $CX_PASSWORD
    CHECKMARX_BASE_URL: $CHECKMARX_SERVER
    CHECKMARX_SCAN_PRESET: "OWASP TOP 10 - 2017"
    CHECKMARX_SETTINGS_OVERRIDE: "true"

    SCA_TENANT: $SCA_TENANT
    SCA_USERNAME: $SCA_USERNAME
    SCA_PASSWORD: $SCA_PASSWORD
    SCA_INCLUDESOURCES: "true"
    SCA_ENABLEDZIPSCAN: "true"
    PARAMS: "--gitlab"

Note the --gitlab parameter, which was missing originally. However, it is required according to this:
https://github.com/checkmarx-ltd/cx-flow/wiki/CxSCA-Integration#zipFolderScan (link does not work but is the correct entry)

The error is: 
Status code: 500, message: 'Failed to get upload URL for sources', response body: "message":"Failed to generate upload URL","type":"Error","code":0
LOG extract
[0KRunning with gitlab-runner 15.3.0~beta.42.gdb7789ca (db7789ca)[0;m
[0K  on blue-5.shared.runners-manager.gitlab.com/default -AzERasQ[0;m
section_start:1659518727:resolve_secrets
[0K[0K[36;1mResolving secrets[0;m[0;m
section_end:1659518727:resolve_secrets
[0Ksection_start:1659518727:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m[0;m
[0KUsing Docker executor with image checkmarx/cx-flow ...[0;m
[0KPulling docker image checkmarx/cx-flow ...[0;m
[0KUsing docker image sha256:166bf67fbc0bc2ca2702ab63600b00b5705f573996f67a7a4ca62e88a099d7a3 for checkmarx/cx-flow with digest checkmarx/cx-flow@sha256:87921d23bae0e388fdf5b4f5cbb71f51058a43b6d0f21b7aafeaee8b24a74866 ...[0;m
section_end:1659518738:prepare_executor
[0Ksection_start:1659518738:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner--azerasq-project-24895950-concurrent-0 via runner-azerasq-shared-1659518655-1ed46b42...
section_end:1659518740:prepare_script
[0Ksection_start:1659518740:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1m$ eval "$CI_PRE_CLONE_SCRIPT"[0;m
[32;1mFetching changes with git depth set to 50...[0;m
Initialized empty Git repository in /builds/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out f794960d as master...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1659518742:get_sources
[0Ksection_start:1659518742:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:166bf67fbc0bc2ca2702ab63600b00b5705f573996f67a7a4ca62e88a099d7a3 for checkmarx/cx-flow with digest checkmarx/cx-flow@sha256:87921d23bae0e388fdf5b4f5cbb71f51058a43b6d0f21b7aafeaee8b24a74866 ...[0;m
[32;1m$ ${CX_FLOW_EXE} --scan --app="${CI_PROJECT_NAME}" --namespace="${CI_PROJECT_NAMESPACE}" --repo-name="${CI_PROJECT_NAME}" --repo-url="${CI_REPOSITORY_URL}" --cx-team="${CX_TEAM}" --cx-project="${CX_PROJECT}" --branch="${CI_COMMIT_BRANCH}" --spring.profiles.active="${CX_FLOW_ENABLED_VULNERABILITY_SCANNERS}" --f=. ${PARAMS}[0;m
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/app/cx-flow.jar!/BOOT-INF/lib/logback-classic-1.2.10.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/app/cx-flow.jar!/BOOT-INF/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
   ___             ___ _
  / __\_  __      / __\ | _____      __
 / /  \ \/ /____ / _\ | |/ _ \ \ /\ / /
/ /___ >  <_____/ /   | | (_) \ V  V /
\____//_/\_\    \/    |_|\___/ \_/\_/

2022-08-03 09:25:47.035  INFO 13 --- [           main] c.c.f.CxFlowApplication                   [] : Starting CxFlowApplication using Java 1.8.0_322 on runner--azerasq-project-24895950-concurrent-0 with PID 13 (/app/cx-flow.jar started by root in /builds/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab)
2022-08-03 09:25:47.051  INFO 13 --- [           main] c.c.f.CxFlowApplication                   [] : The following 1 profile is active: "sca"
2022-08-03 09:25:51.873  INFO 13 --- [           main] ptablePropertiesBeanFactoryPostProcessor  [] : Post-processing PropertySource instances
2022-08-03 09:25:52.102  INFO 13 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource configurationProperties [org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertySource] to AOP Proxy
2022-08-03 09:25:52.106  INFO 13 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource commandLineArgs [org.springframework.core.env.SimpleCommandLinePropertySource] to EncryptableEnumerablePropertySourceWrapper
2022-08-03 09:25:52.107  INFO 13 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource systemProperties [org.springframework.core.env.PropertiesPropertySource] to EncryptableMapPropertySourceWrapper
2022-08-03 09:25:52.114  INFO 13 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource systemEnvironment [org.springframework.boot.env.SystemEnvironmentPropertySourceEnvironmentPostProcessor$OriginAwareSystemEnvironmentPropertySource] to EncryptableSystemEnvironmentPropertySourceWrapper
2022-08-03 09:25:52.115  INFO 13 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource random [org.springframework.boot.env.RandomValuePropertySource] to EncryptablePropertySourceWrapper
2022-08-03 09:25:52.117  INFO 13 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource Config resource 'class path resource [application-sca.yml]' via location 'optional:classpath:/' [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2022-08-03 09:25:52.118  INFO 13 --- [           main] c.u.j.EncryptablePropertySourceConverter  [] : Converting PropertySource Config resource 'class path resource [application.yml]' via location 'optional:classpath:/' [org.springframework.boot.env.OriginTrackedMapPropertySource] to EncryptableMapPropertySourceWrapper
2022-08-03 09:25:52.538  INFO 13 --- [           main] c.u.j.f.DefaultLazyPropertyFilter         [] : Property Filter custom Bean not found with name 'encryptablePropertyFilter'. Initializing Default Property Filter
2022-08-03 09:25:53.894  INFO 13 --- [           main] c.u.j.r.DefaultLazyPropertyResolver       [] : Property Resolver custom Bean not found with name 'encryptablePropertyResolver'. Initializing Default Property Resolver
2022-08-03 09:25:53.906  INFO 13 --- [           main] c.u.j.d.DefaultLazyPropertyDetector       [] : Property Detector custom Bean not found with name 'encryptablePropertyDetector'. Initializing Default Property Detector
2022-08-03 09:26:00.134  INFO 13 --- [           main] o.s.w.s.s.SaajSoapMessageFactory          [] : Creating SAAJ 1.3 MessageFactory with SOAP 1.1 Protocol
2022-08-03 09:26:00.900  WARN 13 --- [           main] j.p.spi                                   [] : javax.persistence.spi::No valid providers found.
2022-08-03 09:26:02.125  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [] : =======BUILD INFO=======
2022-08-03 09:26:02.130  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [] : Version: cx-flow-1.6.35
2022-08-03 09:26:02.131  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [] : Time: 2022-07-28T07:07:31.699Z
2022-08-03 09:26:02.133  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [] : =======================
2022-08-03 09:26:04.628  INFO 13 --- [           main] c.c.f.CxFlowApplication                   [] : Started CxFlowApplication in 20.34 seconds (JVM running for 21.947)
2022-08-03 09:26:04.654  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [YacMjiqn] : Using custom bean implementation  for bug tracking
2022-08-03 09:26:04.667 DEBUG 13 --- [           main] c.c.f.s.ScaConfigurationOverrider         [YacMjiqn] : Initializing SCA configuration in scan request using default configuration properties.
2022-08-03 09:26:04.801  INFO 13 --- [           main] c.c.f.s.ScaFilterFactory                  [YacMjiqn] : Initializing SCA filters.
2022-08-03 09:26:04.807 DEBUG 13 --- [           main] c.c.f.s.ScaFilterFactory                  [YacMjiqn] : Using SCA filters: (SEVERITY: HIGH)
2022-08-03 09:26:04.815  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [YacMjiqn] : Executing scan process
2022-08-03 09:26:04.825  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [YacMjiqn] : Initiating scan using Checkmarx git clone
2022-08-03 09:26:04.826  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [YacMjiqn] : Git url: https://gitlab-ci-token:[MASKED]@gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab.git
2022-08-03 09:26:04.831  INFO 13 --- [           main] c.c.f.s.AbstractASTScanner                [YacMjiqn] : --------------------- Initiating new sca scan ---------------------
2022-08-03 09:26:04.833  INFO 13 --- [           main] c.c.f.s.SCAScanner                        [YacMjiqn] : CxAST-SCA zip scan is enabled
2022-08-03 09:26:04.839  INFO 13 --- [           main] c.c.s.u.CxRepoFileHelper                  [YacMjiqn] : empty token
2022-08-03 09:26:04.840  INFO 13 --- [           main] c.c.s.u.CxRepoFileHelper                  [YacMjiqn] : credentialsProvider without password
2022-08-03 09:26:04.841  INFO 13 --- [           main] c.c.s.u.CxRepoFileHelper                  [YacMjiqn] : Cloning code locally to /tmp/db47be90-4198-4bee-9913-0d9279575050
2022-08-03 09:26:07.910  INFO 13 --- [           main] c.c.s.u.CxRepoFileHelper                  [YacMjiqn] : git: https://oauth2:[MASKED]@gitlab-ci-token:[MASKED]@gitlab.com/jurgen-cx/gitlab-jvl-cxflow/JavaVulnerableLab.git, Cloned successfully
2022-08-03 09:26:07.913 DEBUG 13 --- [           main] c.c.f.s.BugTrackerEventTrigger            [YacMjiqn] : Bug tracker events were not triggered, because bug tracker type is 'CUSTOM'.
2022-08-03 09:26:07.976  INFO 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : Logging into CxAST-SCA
2022-08-03 09:26:10.193  INFO 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : ----------------------------------- Initiating CxAST-SCA Scan:------------------------------------
2022-08-03 09:26:10.193  INFO 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : Getting project by name: 'JavaVulnerableLab-master'
2022-08-03 09:26:10.194  INFO 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : Getting project ID by name: 'JavaVulnerableLab-master'
2022-08-03 09:26:10.521  INFO 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : Project ID: e76f9151-0e99-445c-9951-e07198eb2c53
2022-08-03 09:26:10.521  INFO 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : Project already exists with ID e76f9151-0e99-445c-9951-e07198eb2c53
2022-08-03 09:26:10.522  INFO 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : Using local directory flow.
2022-08-03 09:26:10.522  INFO 13 --- [           main] c.c.s.u.CxRepoFileHelper                  [YacMjiqn] : running zip file
2022-08-03 09:26:10.524  INFO 13 --- [           main] c.c.s.u.z.ZipUtils                        [YacMjiqn] : Creating zip file /tmp/cx.9f0a2d43-3084-48eb-87bd-3e1ddb14c392.zip from contents of path /tmp/db47be90-4198-4bee-9913-0d9279575050
2022-08-03 09:26:10.728  INFO 13 --- [           main] c.c.s.u.z.ZipUtils                        [YacMjiqn] : Successfully created /tmp/cx.9f0a2d43-3084-48eb-87bd-3e1ddb14c392.zip 
2022-08-03 09:26:11.557 ERROR 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : Status code: 500, message: 'Failed to get upload URL for sources', response body: "message":"Failed to generate upload URL","type":"Error","code":0
2022-08-03 09:26:11.558  INFO 13 --- [           main] c.c.s.s.s.ScaScanner                      [YacMjiqn] : Deleting cloned repo zip file: /tmp/cx.9f0a2d43-3084-48eb-87bd-3e1ddb14c392.zip
2022-08-03 09:26:11.564 ERROR 13 --- [           main] c.c.f.s.AbstractASTScanner                [YacMjiqn] : sca scan failed.

com.checkmarx.sdk.exception.ScannerRuntimeException: Error creating scan.
	at com.checkmarx.sdk.service.scanner.AbstractScanner.validateResults(AbstractScanner.java:113)
	at com.checkmarx.sdk.service.scanner.AbstractScanner.executeScan(AbstractScanner.java:61)
	at com.checkmarx.sdk.service.scanner.AbstractScanner.scan(AbstractScanner.java:40)
	at com.checkmarx.flow.service.AbstractASTScanner.scan(AbstractASTScanner.java:44)
	at com.checkmarx.flow.service.AbstractASTScanner.scanCli(AbstractASTScanner.java:60)
	at com.checkmarx.flow.CxFlowRunner.lambda$scanCommon$3(CxFlowRunner.java:621)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:546)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:505)
	at com.checkmarx.flow.CxFlowRunner.runOnActiveScanners(CxFlowRunner.java:690)
	at com.checkmarx.flow.CxFlowRunner.scanCommon(CxFlowRunner.java:621)
	at com.checkmarx.flow.CxFlowRunner.scanCommon(CxFlowRunner.java:598)
	at com.checkmarx.flow.CxFlowRunner.scanRemoteRepo(CxFlowRunner.java:583)
	at com.checkmarx.flow.CxFlowRunner.commandLineRunner(CxFlowRunner.java:462)
	at com.checkmarx.flow.CxFlowRunner.run(CxFlowRunner.java:93)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:762)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:752)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at com.checkmarx.flow.CxFlowApplication.main(CxFlowApplication.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65)

2022-08-03 09:26:11.692  INFO 13 --- [           main] jsonLogger                                [YacMjiqn] : 
2022-08-03 09:26:11.715 ERROR 13 --- [           main] c.c.f.s.AbstractASTScanner                [YacMjiqn] : sca scan failed.
Error creating scan.
2022-08-03 09:26:11.716  INFO 13 --- [           main] c.c.f.CxFlowRunner                        [YacMjiqn] : Finished with exit code: 10
section_end:1659518771:step_script
[0Ksection_start:1659518771:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1659518772:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 10
[0;m

**Comment by itsKedar** [comment]
Please check on our latest version 1.7.0 . If does not work please reopen issue.
