### ISSUE TITLE
Getting "404 Project Not Found" errors on merge request scans

### ISSUE THREAD

**Issue by JPierron** [checkmarx-ltd/cx-flow#944]
## Problem
I'm getting **404 Not Found** errors in the GitLab job logs when running the checkmarx scan job on merge requests.
With the cx-flow options **--logging.level.org.springframework.web.client=TRACE** and **--logging.level.com.checkmarx.flow.custom=TRACE**, we can see it appears that cx-flow gets a 404 on the following url :
https://gitlab.my-company.com/api/v4/projects/1081/merge_requests/10/notes
Although, given url work just fine from a browser.
Also, it's worth noting we don't get this error when cx-flow creates issues on regular scan with the GitLab bug tracker.
```
2022-02-28 17:01:13.033  INFO 24 --- [           main] com.checkmarx.sdk.service.CxAuthService  : Logging into Checkmarx for SOAP token http://checkmarx.my-company.com/cxrestapi/auth/identity/connect/token
2022-02-28 17:01:13.034 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : HTTP POST http://checkmarx.my-company.com/cxrestapi/auth/identity/connect/token
2022-02-28 17:01:13.040 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2022-02-28 17:01:13.041 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Writing [{username=[fdev], password=[[MASKED]], grant_type=[password], scope=[sast_api], client_id=[resource_owner_sast_client], client_secret=[014DF517-39D1-4453-B7B3-9930C563627C]}] as "application/x-www-form-urlencoded"
2022-02-28 17:01:13.106 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Response 200 OK
2022-02-28 17:01:13.108 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Reading to [com.checkmarx.sdk.dto.cx.CxAuthResponse]
2022-02-28 17:01:13.110  INFO 24 --- [           main] com.checkmarx.sdk.service.CxService      : Retrieving report contents of report Id 15631 in XML format
2022-02-28 17:01:13.115 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : HTTP GET http://checkmarx.my-company.com/cxrestapi/reports/sastScan/15631
2022-02-28 17:01:13.116 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Accept=[text/plain, application/json, application/*+json, */*]
2022-02-28 17:01:13.130 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Response 200 OK
2022-02-28 17:01:13.130 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Reading to [java.lang.String] as "application/xml"
2022-02-28 17:01:13.136  INFO 24 --- [           main] com.checkmarx.sdk.service.CxService      : Report downloaded for report Id 15631
2022-02-28 17:01:13.711  INFO 24 --- [           main] com.checkmarx.sdk.service.CxService      : Fetching Scan data for Id 1016172
2022-02-28 17:01:13.715 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : HTTP GET http://checkmarx.my-company.com/cxrestapi/sast/scans/1016172
2022-02-28 17:01:13.716 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Accept=[text/plain, application/json, application/*+json, */*]
2022-02-28 17:01:13.724 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Response 200 OK
2022-02-28 17:01:13.725 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Reading to [java.lang.String] as "application/json;charset=utf-8"
2022-02-28 17:01:13.726  INFO 24 --- [           main] com.checkmarx.sdk.service.CxService      : Fetching custom fields from project ID 739
2022-02-28 17:01:13.727 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : HTTP GET http://checkmarx.my-company.com/cxrestapi/projects/739
2022-02-28 17:01:13.737 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2022-02-28 17:01:13.745 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Response 200 OK
2022-02-28 17:01:13.745 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Reading to [com.checkmarx.sdk.dto.cx.CxProject]
2022-02-28 17:01:13.747 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : HTTP GET http://checkmarx.my-company.com/cxrestapi/sast/scans/1016172/resultsStatistics
2022-02-28 17:01:13.757 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2022-02-28 17:01:13.769 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Response 200 OK
2022-02-28 17:01:13.769 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Reading to [com.checkmarx.sdk.dto.cx.CxScanSummary]
2022-02-28 17:01:13.872  INFO 24 --- [           main] com.checkmarx.flow.utils.HTMLHelper      : Creating Merge/Pull Request Markdown comment
2022-02-28 17:01:13.887 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : HTTP GET https://gitlab.my-company.com/api/v4/projects/1081/merge_requests/13/notes
2022-02-28 17:01:13.888 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Accept=[application/json, application/*+json]
2022-02-28 17:01:13.929 DEBUG 24 --- [           main] o.s.web.client.RestTemplate              : Response 404 NOT_FOUND
2022-02-28 17:01:13.930 ERROR 24 --- [           main] com.checkmarx.flow.service.RepoService   : Error while adding or updating GITLAB repo pull request comment
org.springframework.web.client.HttpClientErrorException$NotFound: 404 Not Found: [{"message":"404 Not found"}]
	at org.springframework.web.client.HttpClientErrorException.create(HttpClientErrorException.java:113)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:184)
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:125)
	...
```
## Details
**GitLab Community Edition** [14.6.0](https://gitlab.com/gitlab-org/gitlab-foss/-/tags/v14.6.0)
**CxFlow** [1.6.19](https://hub.docker.com/layers/checkmarx/cx-flow/1.6.19/images/sha256-5147c656461544f58b5f333bf837ba7e40fd1ddda4a3169b12e2188c89f50869?context=explore)
**CI Checkmarx job :**
```
checkmarx-scan-on-mr:
  image:
    name: checkmarx/cx-flow:1.6.19
    entrypoint: ['']
  before_script:
    - cat ${GITLAB_LOCAL_CA_CERT} > gitlab.cert
    - keytool -import -trustcacerts -alias localca -file gitlab.cert -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit -noprompt
  after_script:
    - ''
  timeout: 1h
  allow_failure: true
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: manual
  script:
    - cat ${CX_FLOW_CONFIG} > application.yml
    - ${CX_FLOW_CMD}
      --spring.config.location=./application.yml
      --scan
      --app="${CI_PROJECT_NAME}"
      --namespace="${CI_PROJECT_NAMESPACE}"
      --repo-name="${CI_PROJECT_NAME}"
      --repo-url="${CI_REPOSITORY_URL}"
      --cx-team="${CHECKMARX_TEAM}"
      --cx-project="${CI_PROJECT_NAME}"
      --branch="${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}"
      --project-id="${CI_PROJECT_ID}"
      --merge-id="${CI_MERGE_REQUEST_IID}"
      --bug-tracker=GITLABMERGE
      --cx-flow.break-build=${CX_BREAK_BUILD}
      --spring.profiles.active="${CX_FLOW_ENABLED_VULNERABILITY_SCANNERS}"
      --f=.
      ${CX_FLOW_PROJECT_OPTS}
```
## Question
This job used to be working fine, and the last update we did was from cx-flow 1.6.17 to 1.6.19.
We tried with cx-flow 1.16.26 (as the base java image used in 1.6.27+ has changed, and we will have to tweak our configuration a bit regarding certificates imports).
Don't know if i'm missing somthing here or if this is a bug.

**Comment by JPierron** [comment]
Issue was on our part.
We didn't grant our gitlab Checkmarx bot user suffiscient access level (which is Reporter).
